/*===- UnicodeCaseFold.c - Unicode case folding ------------------*- C -*-===*\
|*                                                                            *|
|* Generated by utils/unicode-case-fold.py from Unicode case folding DB at    *|
|*    http://www.unicode.org/Public/15.0.0/ucd/CaseFolding.txt               *|
|*                                                                            *|
\*===----------------------------------------------------------------------===*/
#include "include/csupport/lunicode_lcase_lfold.h"

int csupport_fold_char_simple(int C) {
  if (C < 0x0041)
    return C;
  if (C <= 0x005a)
    return C + 32;
  if (C == 0x00b5)
    return 0x03bc;
  if (C < 0x00c0)
    return C;
  if (C <= 0x00d6)
    return C + 32;
  if (C < 0x00d8)
    return C;
  if (C <= 0x00de)
    return C + 32;
  if (C < 0x0100)
    return C;
  if (C <= 0x012e)
    return C | 1;
  if (C < 0x0132)
    return C;
  if (C <= 0x0136)
    return C | 1;
  if (C < 0x0139)
    return C;
  if (C <= 0x0147 && C % 2 == 1)
    return C + 1;
  if (C < 0x014a)
    return C;
  if (C <= 0x0176)
    return C | 1;
  if (C == 0x0178)
    return 0x00ff;
  if (C < 0x0179)
    return C;
  if (C <= 0x017d && C % 2 == 1)
    return C + 1;
  if (C == 0x017f)
    return 0x0073;
  if (C == 0x0181)
    return 0x0253;
  if (C < 0x0182)
    return C;
  if (C <= 0x0184)
    return C | 1;
  if (C == 0x0186)
    return 0x0254;
  if (C == 0x0187)
    return 0x0188;
  if (C < 0x0189)
    return C;
  if (C <= 0x018a)
    return C + 205;
  if (C == 0x018b)
    return 0x018c;
  if (C == 0x018e)
    return 0x01dd;
  if (C == 0x018f)
    return 0x0259;
  if (C == 0x0190)
    return 0x025b;
  if (C == 0x0191)
    return 0x0192;
  if (C == 0x0193)
    return 0x0260;
  if (C == 0x0194)
    return 0x0263;
  if (C == 0x0196)
    return 0x0269;
  if (C == 0x0197)
    return 0x0268;
  if (C == 0x0198)
    return 0x0199;
  if (C == 0x019c)
    return 0x026f;
  if (C == 0x019d)
    return 0x0272;
  if (C == 0x019f)
    return 0x0275;
  if (C < 0x01a0)
    return C;
  if (C <= 0x01a4)
    return C | 1;
  if (C == 0x01a6)
    return 0x0280;
  if (C == 0x01a7)
    return 0x01a8;
  if (C == 0x01a9)
    return 0x0283;
  if (C == 0x01ac)
    return 0x01ad;
  if (C == 0x01ae)
    return 0x0288;
  if (C == 0x01af)
    return 0x01b0;
  if (C < 0x01b1)
    return C;
  if (C <= 0x01b2)
    return C + 217;
  if (C < 0x01b3)
    return C;
  if (C <= 0x01b5 && C % 2 == 1)
    return C + 1;
  if (C == 0x01b7)
    return 0x0292;
  if (C < 0x01b8)
    return C;
  if (C <= 0x01bc && C % 4 == 0)
    return C + 1;
  if (C == 0x01c4)
    return 0x01c6;
  if (C == 0x01c5)
    return 0x01c6;
  if (C == 0x01c7)
    return 0x01c9;
  if (C == 0x01c8)
    return 0x01c9;
  if (C == 0x01ca)
    return 0x01cc;
  if (C < 0x01cb)
    return C;
  if (C <= 0x01db && C % 2 == 1)
    return C + 1;
  if (C < 0x01de)
    return C;
  if (C <= 0x01ee)
    return C | 1;
  if (C == 0x01f1)
    return 0x01f3;
  if (C < 0x01f2)
    return C;
  if (C <= 0x01f4)
    return C | 1;
  if (C == 0x01f6)
    return 0x0195;
  if (C == 0x01f7)
    return 0x01bf;
  if (C < 0x01f8)
    return C;
  if (C <= 0x021e)
    return C | 1;
  if (C == 0x0220)
    return 0x019e;
  if (C < 0x0222)
    return C;
  if (C <= 0x0232)
    return C | 1;
  if (C == 0x023a)
    return 0x2c65;
  if (C == 0x023b)
    return 0x023c;
  if (C == 0x023d)
    return 0x019a;
  if (C == 0x023e)
    return 0x2c66;
  if (C == 0x0241)
    return 0x0242;
  if (C == 0x0243)
    return 0x0180;
  if (C == 0x0244)
    return 0x0289;
  if (C == 0x0245)
    return 0x028c;
  if (C < 0x0246)
    return C;
  if (C <= 0x024e)
    return C | 1;
  if (C == 0x0345)
    return 0x03b9;
  if (C < 0x0370)
    return C;
  if (C <= 0x0372)
    return C | 1;
  if (C == 0x0376)
    return 0x0377;
  if (C == 0x037f)
    return 0x03f3;
  if (C == 0x0386)
    return 0x03ac;
  if (C < 0x0388)
    return C;
  if (C <= 0x038a)
    return C + 37;
  if (C == 0x038c)
    return 0x03cc;
  if (C < 0x038e)
    return C;
  if (C <= 0x038f)
    return C + 63;
  if (C < 0x0391)
    return C;
  if (C <= 0x03a1)
    return C + 32;
  if (C < 0x03a3)
    return C;
  if (C <= 0x03ab)
    return C + 32;
  if (C == 0x03c2)
    return 0x03c3;
  if (C == 0x03cf)
    return 0x03d7;
  if (C == 0x03d0)
    return 0x03b2;
  if (C == 0x03d1)
    return 0x03b8;
  if (C == 0x03d5)
    return 0x03c6;
  if (C == 0x03d6)
    return 0x03c0;
  if (C < 0x03d8)
    return C;
  if (C <= 0x03ee)
    return C | 1;
  if (C == 0x03f0)
    return 0x03ba;
  if (C == 0x03f1)
    return 0x03c1;
  if (C == 0x03f4)
    return 0x03b8;
  if (C == 0x03f5)
    return 0x03b5;
  if (C == 0x03f7)
    return 0x03f8;
  if (C == 0x03f9)
    return 0x03f2;
  if (C == 0x03fa)
    return 0x03fb;
  if (C < 0x03fd)
    return C;
  if (C <= 0x03ff)
    return C + -130;
  if (C < 0x0400)
    return C;
  if (C <= 0x040f)
    return C + 80;
  if (C < 0x0410)
    return C;
  if (C <= 0x042f)
    return C + 32;
  if (C < 0x0460)
    return C;
  if (C <= 0x0480)
    return C | 1;
  if (C < 0x048a)
    return C;
  if (C <= 0x04be)
    return C | 1;
  if (C == 0x04c0)
    return 0x04cf;
  if (C < 0x04c1)
    return C;
  if (C <= 0x04cd && C % 2 == 1)
    return C + 1;
  if (C < 0x04d0)
    return C;
  if (C <= 0x052e)
    return C | 1;
  if (C < 0x0531)
    return C;
  if (C <= 0x0556)
    return C + 48;
  if (C < 0x10a0)
    return C;
  if (C <= 0x10c5)
    return C + 7264;
  if (C < 0x10c7)
    return C;
  if (C <= 0x10cd && C % 6 == 5)
    return C + 7264;
  if (C < 0x13f8)
    return C;
  if (C <= 0x13fd)
    return C + -8;
  if (C == 0x1c80)
    return 0x0432;
  if (C == 0x1c81)
    return 0x0434;
  if (C == 0x1c82)
    return 0x043e;
  if (C < 0x1c83)
    return C;
  if (C <= 0x1c84)
    return C + -6210;
  if (C == 0x1c85)
    return 0x0442;
  if (C == 0x1c86)
    return 0x044a;
  if (C == 0x1c87)
    return 0x0463;
  if (C == 0x1c88)
    return 0xa64b;
  if (C < 0x1c90)
    return C;
  if (C <= 0x1cba)
    return C + -3008;
  if (C < 0x1cbd)
    return C;
  if (C <= 0x1cbf)
    return C + -3008;
  if (C < 0x1e00)
    return C;
  if (C <= 0x1e94)
    return C | 1;
  if (C == 0x1e9b)
    return 0x1e61;
  if (C == 0x1e9e)
    return 0x00df;
  if (C < 0x1ea0)
    return C;
  if (C <= 0x1efe)
    return C | 1;
  if (C < 0x1f08)
    return C;
  if (C <= 0x1f0f)
    return C + -8;
  if (C < 0x1f18)
    return C;
  if (C <= 0x1f1d)
    return C + -8;
  if (C < 0x1f28)
    return C;
  if (C <= 0x1f2f)
    return C + -8;
  if (C < 0x1f38)
    return C;
  if (C <= 0x1f3f)
    return C + -8;
  if (C < 0x1f48)
    return C;
  if (C <= 0x1f4d)
    return C + -8;
  if (C < 0x1f59)
    return C;
  if (C <= 0x1f5f && C % 2 == 1)
    return C + -8;
  if (C < 0x1f68)
    return C;
  if (C <= 0x1f6f)
    return C + -8;
  if (C < 0x1f88)
    return C;
  if (C <= 0x1f8f)
    return C + -8;
  if (C < 0x1f98)
    return C;
  if (C <= 0x1f9f)
    return C + -8;
  if (C < 0x1fa8)
    return C;
  if (C <= 0x1faf)
    return C + -8;
  if (C < 0x1fb8)
    return C;
  if (C <= 0x1fb9)
    return C + -8;
  if (C < 0x1fba)
    return C;
  if (C <= 0x1fbb)
    return C + -74;
  if (C == 0x1fbc)
    return 0x1fb3;
  if (C == 0x1fbe)
    return 0x03b9;
  if (C < 0x1fc8)
    return C;
  if (C <= 0x1fcb)
    return C + -86;
  if (C == 0x1fcc)
    return 0x1fc3;
  if (C < 0x1fd8)
    return C;
  if (C <= 0x1fd9)
    return C + -8;
  if (C < 0x1fda)
    return C;
  if (C <= 0x1fdb)
    return C + -100;
  if (C < 0x1fe8)
    return C;
  if (C <= 0x1fe9)
    return C + -8;
  if (C < 0x1fea)
    return C;
  if (C <= 0x1feb)
    return C + -112;
  if (C == 0x1fec)
    return 0x1fe5;
  if (C < 0x1ff8)
    return C;
  if (C <= 0x1ff9)
    return C + -128;
  if (C < 0x1ffa)
    return C;
  if (C <= 0x1ffb)
    return C + -126;
  if (C == 0x1ffc)
    return 0x1ff3;
  if (C == 0x2126)
    return 0x03c9;
  if (C == 0x212a)
    return 0x006b;
  if (C == 0x212b)
    return 0x00e5;
  if (C == 0x2132)
    return 0x214e;
  if (C < 0x2160)
    return C;
  if (C <= 0x216f)
    return C + 16;
  if (C == 0x2183)
    return 0x2184;
  if (C < 0x24b6)
    return C;
  if (C <= 0x24cf)
    return C + 26;
  if (C < 0x2c00)
    return C;
  if (C <= 0x2c2f)
    return C + 48;
  if (C == 0x2c60)
    return 0x2c61;
  if (C == 0x2c62)
    return 0x026b;
  if (C == 0x2c63)
    return 0x1d7d;
  if (C == 0x2c64)
    return 0x027d;
  if (C < 0x2c67)
    return C;
  if (C <= 0x2c6b && C % 2 == 1)
    return C + 1;
  if (C == 0x2c6d)
    return 0x0251;
  if (C == 0x2c6e)
    return 0x0271;
  if (C == 0x2c6f)
    return 0x0250;
  if (C == 0x2c70)
    return 0x0252;
  if (C < 0x2c72)
    return C;
  if (C <= 0x2c75 && C % 3 == 2)
    return C + 1;
  if (C < 0x2c7e)
    return C;
  if (C <= 0x2c7f)
    return C + -10815;
  if (C < 0x2c80)
    return C;
  if (C <= 0x2ce2)
    return C | 1;
  if (C < 0x2ceb)
    return C;
  if (C <= 0x2ced && C % 2 == 1)
    return C + 1;
  if (C < 0x2cf2)
    return C;
  if (C <= 0xa640 && C % 31054 == 11506)
    return C + 1;
  if (C < 0xa642)
    return C;
  if (C <= 0xa66c)
    return C | 1;
  if (C < 0xa680)
    return C;
  if (C <= 0xa69a)
    return C | 1;
  if (C < 0xa722)
    return C;
  if (C <= 0xa72e)
    return C | 1;
  if (C < 0xa732)
    return C;
  if (C <= 0xa76e)
    return C | 1;
  if (C < 0xa779)
    return C;
  if (C <= 0xa77b && C % 2 == 1)
    return C + 1;
  if (C == 0xa77d)
    return 0x1d79;
  if (C < 0xa77e)
    return C;
  if (C <= 0xa786)
    return C | 1;
  if (C == 0xa78b)
    return 0xa78c;
  if (C == 0xa78d)
    return 0x0265;
  if (C < 0xa790)
    return C;
  if (C <= 0xa792)
    return C | 1;
  if (C < 0xa796)
    return C;
  if (C <= 0xa7a8)
    return C | 1;
  if (C == 0xa7aa)
    return 0x0266;
  if (C == 0xa7ab)
    return 0x025c;
  if (C == 0xa7ac)
    return 0x0261;
  if (C == 0xa7ad)
    return 0x026c;
  if (C == 0xa7ae)
    return 0x026a;
  if (C == 0xa7b0)
    return 0x029e;
  if (C == 0xa7b1)
    return 0x0287;
  if (C == 0xa7b2)
    return 0x029d;
  if (C == 0xa7b3)
    return 0xab53;
  if (C < 0xa7b4)
    return C;
  if (C <= 0xa7c2)
    return C | 1;
  if (C == 0xa7c4)
    return 0xa794;
  if (C == 0xa7c5)
    return 0x0282;
  if (C == 0xa7c6)
    return 0x1d8e;
  if (C < 0xa7c7)
    return C;
  if (C <= 0xa7c9 && C % 2 == 1)
    return C + 1;
  if (C < 0xa7d0)
    return C;
  if (C <= 0xa7d6 && C % 6 == 0)
    return C + 1;
  if (C < 0xa7d8)
    return C;
  if (C <= 0xa7f5 && C % 29 == 19)
    return C + 1;
  if (C < 0xab70)
    return C;
  if (C <= 0xabbf)
    return C + -38864;
  if (C < 0xff21)
    return C;
  if (C <= 0xff3a)
    return C + 32;
  if (C < 0x10400)
    return C;
  if (C <= 0x10427)
    return C + 40;
  if (C < 0x104b0)
    return C;
  if (C <= 0x104d3)
    return C + 40;
  if (C < 0x10570)
    return C;
  if (C <= 0x1057a)
    return C + 39;
  if (C < 0x1057c)
    return C;
  if (C <= 0x1058a)
    return C + 39;
  if (C < 0x1058c)
    return C;
  if (C <= 0x10592)
    return C + 39;
  if (C < 0x10594)
    return C;
  if (C <= 0x10595)
    return C + 39;
  if (C < 0x10c80)
    return C;
  if (C <= 0x10cb2)
    return C + 64;
  if (C < 0x118a0)
    return C;
  if (C <= 0x118bf)
    return C + 32;
  if (C < 0x16e40)
    return C;
  if (C <= 0x16e5f)
    return C + 32;
  if (C < 0x1e900)
    return C;
  if (C <= 0x1e921)
    return C + 34;

  return C;
}
