#include "neverc/Foundation/Target/TargetInfo.h"
#include "neverc/Scan/LexDiag.h"
#include "neverc/Scan/LiteralParser.h"
#include "neverc/Scan/PrepEngine.h"
#include "llvm/ADT/APSInt.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/SaveAndRestore.h"
#include <cassert>

using namespace neverc;

// ===----------------------------------------------------------------------===
// Value representation & defined() evaluation
// ===----------------------------------------------------------------------===

namespace {

class CondExprValue {
  SourceRange Range;
  IdentifierInfo *II = nullptr;

public:
  llvm::APSInt Val;

  explicit CondExprValue(unsigned BitWidth) : Val(BitWidth) {}

  IdentifierInfo *getIdentifier() const { return II; }
  void setIdentifier(IdentifierInfo *NewII) { this->II = NewII; }

  unsigned getBitWidth() const { return Val.getBitWidth(); }
  bool isUnsigned() const { return Val.isUnsigned(); }

  SourceRange getRange() const { return Range; }

  void setRange(SourceLocation L) {
    Range.setBegin(L);
    Range.setEnd(L);
  }
  void setRange(SourceLocation B, SourceLocation E) {
    Range.setBegin(B);
    Range.setEnd(E);
  }
  void setBegin(SourceLocation L) { Range.setBegin(L); }
  void setEnd(SourceLocation L) { Range.setEnd(L); }
};

bool evaluateBinaryCondition(CondExprValue &LHS, unsigned MinPrec,
                             Token &PeekTok, bool ValueLive,
                             bool &IncludedUndefinedIds, PrepEngine &PP);

struct MacroDefinedState {
  enum TrackerKind {
    DefinedMacro,    // defined(X)
    NotDefinedMacro, // !defined(X)
    Unknown          // Something else.
  } State;
  IdentifierInfo *TheMacro;
  bool IncludedUndefinedIds = false;
};

bool evaluateDefinedExpr(CondExprValue &Result, Token &PeekTok,
                         MacroDefinedState &DT, bool ValueLive,
                         PrepEngine &PP) {
  SourceLocation beginLoc(PeekTok.getLocation());
  Result.setBegin(beginLoc);

  PP.LexRawSkipComments(PeekTok);

  SourceLocation LParenLoc;
  if (PeekTok.is(tok::l_paren)) {
    LParenLoc = PeekTok.getLocation();
    PP.LexRawSkipComments(PeekTok);
  }

  if (PP.validateMacroName(PeekTok, MU_Other))
    return true;

  IdentifierInfo *II = PeekTok.getIdentifierInfo();
  MacroDefinition Macro = PP.getMacroDefinition(II);
  Result.Val = !!Macro;
  Result.Val.setIsUnsigned(false);
  DT.IncludedUndefinedIds = !Macro;

  PP.checkMacroWarnings(PeekTok);

  if (Result.Val != 0 && ValueLive)
    PP.setMacroUsed(Macro.getMacroRecord());

  Token macroToken(PeekTok);

  if (LParenLoc.isValid()) {
    Result.setEnd(PeekTok.getLocation());
    PP.LexRawSkipComments(PeekTok);

    if (PeekTok.isNot(tok::r_paren)) {
      PP.Diag(PeekTok.getLocation(), diag::err_pp_expected_after)
          << "'defined'" << tok::r_paren;
      PP.Diag(LParenLoc, diag::note_matching) << tok::l_paren;
      return true;
    }
    PP.LexSkipComments(PeekTok);
    Result.setEnd(PeekTok.getLocation());
  } else {
    Result.setEnd(PeekTok.getLocation());
    PP.LexSkipComments(PeekTok);
  }

  // UB: 'defined' generated by macro expansion ([cpp.cond]p4).
  if (LLVM_UNLIKELY(beginLoc.isMacroID())) {
    bool IsFunctionTypeMacro =
        PP.getSourceManager()
            .getSLocEntry(PP.getSourceManager().getFileID(beginLoc))
            .getExpansion()
            .isFunctionMacroExpansion();
    if (IsFunctionTypeMacro)
      PP.Diag(beginLoc, diag::warn_defined_in_function_type_macro);
    else
      PP.Diag(beginLoc, diag::warn_defined_in_object_type_macro);
  }

  if (PrepObserver *Callbacks = PP.getObserver()) {
    Callbacks->Defined(macroToken, Macro,
                       SourceRange(beginLoc, PeekTok.getLocation()));
  }

  DT.State = MacroDefinedState::DefinedMacro;
  DT.TheMacro = II;
  return false;
}

__attribute__((hot)) bool
evaluateConditionAtom(CondExprValue &Result, Token &PeekTok,
                      MacroDefinedState &DT, bool ValueLive, PrepEngine &PP) {
  DT.State = MacroDefinedState::Unknown;

  Result.setIdentifier(nullptr);

  const tok::TokenKind Kind = PeekTok.getKind();

  if (LLVM_LIKELY(Kind == tok::numeric_constant))
    goto handle_numeric;

  switch (Kind) {
  default:
    if (IdentifierInfo *II = PeekTok.getIdentifierInfo()) {
      if (LLVM_UNLIKELY(II->isStr("defined")))
        return evaluateDefinedExpr(Result, PeekTok, DT, ValueLive, PP);

      if (ValueLive) {
        PP.Diag(PeekTok, diag::warn_pp_undef_identifier) << II;

        const DiagnosticsEngine &DiagEngine = PP.getDiagnostics();
        if (DiagEngine.isIgnored(diag::warn_pp_undef_identifier,
                                 PeekTok.getLocation())) {
          const auto &UndefPrefixes =
              DiagEngine.getDiagnosticOptions().UndefPrefixes;
          const llvm::StringRef IdentifierName = II->getName();
          if (llvm::any_of(UndefPrefixes,
                           [&IdentifierName](const std::string &Prefix) {
                             return IdentifierName.starts_with(Prefix);
                           }))
            PP.Diag(PeekTok, diag::warn_pp_undef_prefix)
                << AddFlagValue{llvm::join(UndefPrefixes, ",")} << II;
        }
      }
      Result.Val = 0;
      Result.Val.setIsUnsigned(false);
      Result.setIdentifier(II);
      Result.setRange(PeekTok.getLocation());
      DT.IncludedUndefinedIds = true;
      PP.LexSkipComments(PeekTok);
      return false;
    }
    PP.Diag(PeekTok, diag::err_pp_expr_bad_token_start_expr);
    return true;
  case tok::eod:
  case tok::r_paren:
    PP.Diag(PeekTok, diag::err_pp_expected_value_in_expr);
    return true;
  case tok::numeric_constant:
  handle_numeric: {
    llvm::SmallString<64> IntegerBuffer;
    bool NumberInvalid = false;
    llvm::StringRef Spelling =
        PP.getSpelling(PeekTok, IntegerBuffer, &NumberInvalid);
    if (NumberInvalid)
      return true;

    NumericLiteralParser Literal(Spelling, PeekTok.getLocation(),
                                 PP.getSourceManager(), PP.getLangOpts(),
                                 PP.getTargetInfo(), PP.getDiagnostics());
    if (Literal.hadError)
      return true;

    if (Literal.isFloatingLiteral() || Literal.isImaginary) {
      PP.Diag(PeekTok, diag::err_pp_illegal_floating_literal);
      return true;
    }
    assert(Literal.isIntegerLiteral() && "Unknown ppnumber");

    if (!PP.getLangOpts().C99 && Literal.isLongLong)
      PP.Diag(PeekTok, diag::ext_c99_longlong);

    if (Literal.isSizeT)
      PP.Diag(PeekTok, diag::err_size_t_suffix);

    if (Literal.isBitInt)
      PP.Diag(PeekTok, PP.getLangOpts().C23
                           ? diag::warn_c23_compat_bitint_suffix
                           : diag::ext_c23_bitint_suffix);

    if (Literal.getIntegerValue(Result.Val)) {
      if (ValueLive)
        PP.Diag(PeekTok, diag::err_integer_literal_too_large)
            << /* Unsigned */ 1;
      Result.Val.setIsUnsigned(true);
    } else {
      Result.Val.setIsUnsigned(Literal.isUnsigned);
      // Non-decimal literals are implicitly unsigned on signed overflow.
      if (!Literal.isUnsigned && Result.Val.isNegative()) {
        if (ValueLive && Literal.getRadix() == 10)
          PP.Diag(PeekTok, diag::ext_integer_literal_too_large_for_signed);
        Result.Val.setIsUnsigned(true);
      }
    }

    Result.setRange(PeekTok.getLocation());
    PP.LexSkipComments(PeekTok);
    return false;
  }
  case tok::char_constant:         // 'x'
  case tok::wide_char_constant:    // L'x'
  case tok::utf8_char_constant:    // u8'x'
  case tok::utf16_char_constant:   // u'x'
  case tok::utf32_char_constant: { // U'x'
    llvm::SmallString<32> CharBuffer;
    bool CharInvalid = false;
    llvm::StringRef ThisTok = PP.getSpelling(PeekTok, CharBuffer, &CharInvalid);
    if (CharInvalid)
      return true;

    CharLiteralParser Literal(ThisTok.begin(), ThisTok.end(),
                              PeekTok.getLocation(), PP, PeekTok.getKind());
    if (Literal.hadError())
      return true; // A diagnostic was already emitted.

    const TargetInfo &TI = PP.getTargetInfo();
    unsigned NumBits;
    if (Literal.isMultiChar())
      NumBits = TI.getIntWidth();
    else if (Literal.isWide())
      NumBits = TI.getWCharWidth();
    else if (Literal.isUTF16())
      NumBits = TI.getChar16Width();
    else if (Literal.isUTF32())
      NumBits = TI.getChar32Width();
    else
      NumBits = TI.getCharWidth();

    llvm::APSInt Val(NumBits);
    Val = Literal.getValue();
    if (Literal.isWide())
      Val.setIsUnsigned(!TargetInfo::isTypeSigned(TI.getWCharType()));
    else if (Literal.isUTF16() || Literal.isUTF32())
      Val.setIsUnsigned(true);
    else if (Literal.isUTF8())
      Val.setIsUnsigned(true);
    else
      Val.setIsUnsigned(!PP.getLangOpts().CharIsSigned);

    if (Result.Val.getBitWidth() > Val.getBitWidth()) {
      Result.Val = Val.extend(Result.Val.getBitWidth());
    } else {
      assert(Result.Val.getBitWidth() == Val.getBitWidth() &&
             "intmax_t smaller than char/wchar_t?");
      Result.Val = Val;
    }

    Result.setRange(PeekTok.getLocation());
    PP.LexSkipComments(PeekTok);
    return false;
  }
  case tok::l_paren: {
    SourceLocation Start = PeekTok.getLocation();
    PP.LexSkipComments(PeekTok); // Eat the (.
    // Parse the value and if there are any binary operators involved, parse
    // them.
    if (evaluateConditionAtom(Result, PeekTok, DT, ValueLive, PP))
      return true;

    if (PeekTok.is(tok::r_paren)) {
      // Parenthesized single value -- keep DT as-is.
    } else {
      if (evaluateBinaryCondition(Result, 1, PeekTok, ValueLive,
                                  DT.IncludedUndefinedIds, PP))
        return true;

      if (PeekTok.isNot(tok::r_paren)) {
        PP.Diag(PeekTok.getLocation(), diag::err_pp_expected_rparen)
            << Result.getRange();
        PP.Diag(Start, diag::note_matching) << tok::l_paren;
        return true;
      }
      DT.State = MacroDefinedState::Unknown;
    }
    Result.setRange(Start, PeekTok.getLocation());
    Result.setIdentifier(nullptr);
    PP.LexSkipComments(PeekTok);
    return false;
  }
  case tok::plus: {
    SourceLocation Start = PeekTok.getLocation();
    PP.LexSkipComments(PeekTok);
    if (evaluateConditionAtom(Result, PeekTok, DT, ValueLive, PP))
      return true;
    Result.setBegin(Start);
    Result.setIdentifier(nullptr);
    return false;
  }
  case tok::minus: {
    SourceLocation Loc = PeekTok.getLocation();
    PP.LexSkipComments(PeekTok);
    if (evaluateConditionAtom(Result, PeekTok, DT, ValueLive, PP))
      return true;
    Result.setBegin(Loc);
    Result.setIdentifier(nullptr);

    // Sign of result matches the operand.
    Result.Val = -Result.Val;

    // -MININT is the only thing that overflows.  Unsigned never overflows.
    bool Overflow = !Result.isUnsigned() && Result.Val.isMinSignedValue();

    // If this operator is live and overflowed, report the issue.
    if (Overflow && ValueLive)
      PP.Diag(Loc, diag::warn_pp_expr_overflow) << Result.getRange();

    DT.State = MacroDefinedState::Unknown;
    return false;
  }

  case tok::tilde: {
    SourceLocation Start = PeekTok.getLocation();
    PP.LexSkipComments(PeekTok);
    if (evaluateConditionAtom(Result, PeekTok, DT, ValueLive, PP))
      return true;
    Result.setBegin(Start);
    Result.setIdentifier(nullptr);

    // Sign of result matches the operand.
    Result.Val = ~Result.Val;
    DT.State = MacroDefinedState::Unknown;
    return false;
  }

  case tok::exclaim: {
    SourceLocation Start = PeekTok.getLocation();
    PP.LexSkipComments(PeekTok);
    if (evaluateConditionAtom(Result, PeekTok, DT, ValueLive, PP))
      return true;
    Result.setBegin(Start);
    Result.Val = !Result.Val;
    // Logical-NOT always yields signed int.
    Result.Val.setIsUnsigned(false);
    Result.setIdentifier(nullptr);

    if (DT.State == MacroDefinedState::DefinedMacro)
      DT.State = MacroDefinedState::NotDefinedMacro;
    else if (DT.State == MacroDefinedState::NotDefinedMacro)
      DT.State = MacroDefinedState::DefinedMacro;
    return false;
  }
  case tok::kw_true:
  case tok::kw_false:
    Result.Val = PeekTok.getKind() == tok::kw_true;
    Result.Val.setIsUnsigned(false); // "0" is signed intmax_t 0.
    Result.setIdentifier(PeekTok.getIdentifierInfo());
    Result.setRange(PeekTok.getLocation());
    PP.LexSkipComments(PeekTok);
    return false;
  }
}

// ===----------------------------------------------------------------------===
// Operator precedence & binary expression evaluation
// ===----------------------------------------------------------------------===

namespace {

struct PrecedenceTable {
  uint8_t Data[tok::NUM_TOKENS];
  constexpr PrecedenceTable() : Data{} {
    for (unsigned i = 0; i < tok::NUM_TOKENS; ++i)
      Data[i] = 0xFF;
    Data[tok::percent] = 14;
    Data[tok::slash] = 14;
    Data[tok::star] = 14;
    Data[tok::plus] = 13;
    Data[tok::minus] = 13;
    Data[tok::lessless] = 12;
    Data[tok::greatergreater] = 12;
    Data[tok::lessequal] = 11;
    Data[tok::less] = 11;
    Data[tok::greaterequal] = 11;
    Data[tok::greater] = 11;
    Data[tok::exclaimequal] = 10;
    Data[tok::equalequal] = 10;
    Data[tok::amp] = 9;
    Data[tok::caret] = 8;
    Data[tok::pipe] = 7;
    Data[tok::ampamp] = 6;
    Data[tok::pipepipe] = 5;
    Data[tok::question] = 4;
    Data[tok::comma] = 3;
    Data[tok::colon] = 2;
    Data[tok::r_paren] = 0;
    Data[tok::eod] = 0;
  }
};

constexpr PrecedenceTable PrecLUT;

} // namespace

LLVM_ATTRIBUTE_ALWAYS_INLINE static unsigned
getDirectivePrecedence(tok::TokenKind Kind) {
  unsigned K = static_cast<unsigned>(Kind);
  if (LLVM_UNLIKELY(K >= tok::NUM_TOKENS))
    return ~0U;
  unsigned P = PrecLUT.Data[K];
  return P == 0xFF ? ~0U : P;
}

void reportInvalidCondOperator(PrepEngine &PP, CondExprValue &LHS, Token &Tok) {
  if (Tok.is(tok::l_paren) && LHS.getIdentifier())
    PP.Diag(LHS.getRange().getBegin(), diag::err_pp_expr_bad_token_lparen)
        << LHS.getIdentifier();
  else
    PP.Diag(Tok.getLocation(), diag::err_pp_expr_bad_token_binop)
        << LHS.getRange();
}

bool evaluateBinaryCondition(CondExprValue &LHS, unsigned MinPrec,
                             Token &PeekTok, bool ValueLive,
                             bool &IncludedUndefinedIds, PrepEngine &PP) {
  unsigned PeekPrec = getDirectivePrecedence(PeekTok.getKind());
  if (LLVM_UNLIKELY(PeekPrec == ~0U)) {
    reportInvalidCondOperator(PP, LHS, PeekTok);
    return true;
  }

  while (true) {
    if (PeekPrec < MinPrec)
      return false;

    tok::TokenKind Operator = PeekTok.getKind();

    // Short-circuit evaluation for &&, ||, ?:.
    bool RHSIsLive;
    if (Operator == tok::ampamp && LHS.Val == 0)
      RHSIsLive = false;
    else if (Operator == tok::pipepipe && LHS.Val != 0)
      RHSIsLive = false;
    else if (Operator == tok::question && LHS.Val == 0)
      RHSIsLive = false;
    else
      RHSIsLive = ValueLive;

    SourceLocation OpLoc = PeekTok.getLocation();
    PP.LexSkipComments(PeekTok);

    CondExprValue RHS(LHS.getBitWidth());
    MacroDefinedState DT;
    if (evaluateConditionAtom(RHS, PeekTok, DT, RHSIsLive, PP))
      return true;
    IncludedUndefinedIds = DT.IncludedUndefinedIds;

    unsigned ThisPrec = PeekPrec;
    PeekPrec = getDirectivePrecedence(PeekTok.getKind());

    if (LLVM_UNLIKELY(PeekPrec == ~0U)) {
      reportInvalidCondOperator(PP, RHS, PeekTok);
      return true;
    }

    // Ternary RHS consumes as a full expression; others climb at +1.
    unsigned RHSPrec;
    if (Operator == tok::question)
      RHSPrec = getDirectivePrecedence(tok::comma);
    else
      RHSPrec = ThisPrec + 1;

    if (PeekPrec >= RHSPrec) {
      if (evaluateBinaryCondition(RHS, RHSPrec, PeekTok, RHSIsLive,
                                  IncludedUndefinedIds, PP))
        return true;
      PeekPrec = getDirectivePrecedence(PeekTok.getKind());
    }
    assert(PeekPrec <= ThisPrec && "Recursion didn't work!");

    llvm::APSInt Res(LHS.getBitWidth());
    switch (Operator) {
    case tok::question:
    case tok::lessless:
    case tok::greatergreater:
    case tok::comma:
    case tok::pipepipe:
    case tok::ampamp:
      break;
    default:
      // Usual arithmetic conversion: unsigned if either operand is unsigned.
      Res.setIsUnsigned(LHS.isUnsigned() || RHS.isUnsigned());
      if (ValueLive && Res.isUnsigned()) {
        if (!LHS.isUnsigned() && LHS.Val.isNegative())
          PP.Diag(OpLoc, diag::warn_pp_convert_to_positive)
              << 0
              << toString(LHS.Val, 10, true) + " to " +
                     toString(LHS.Val, 10, false)
              << LHS.getRange() << RHS.getRange();
        if (!RHS.isUnsigned() && RHS.Val.isNegative())
          PP.Diag(OpLoc, diag::warn_pp_convert_to_positive)
              << 1
              << toString(RHS.Val, 10, true) + " to " +
                     toString(RHS.Val, 10, false)
              << LHS.getRange() << RHS.getRange();
      }
      LHS.Val.setIsUnsigned(Res.isUnsigned());
      RHS.Val.setIsUnsigned(Res.isUnsigned());
    }

    bool Overflow = false;
    switch (Operator) {
    default:
      llvm_unreachable("Unknown operator token!");
    case tok::percent:
      if (RHS.Val != 0)
        Res = LHS.Val % RHS.Val;
      else if (ValueLive) {
        PP.Diag(OpLoc, diag::err_pp_remainder_by_zero)
            << LHS.getRange() << RHS.getRange();
        return true;
      }
      break;
    case tok::slash:
      if (RHS.Val != 0) {
        if (LHS.Val.isSigned())
          Res = llvm::APSInt(LHS.Val.sdiv_ov(RHS.Val, Overflow), false);
        else
          Res = LHS.Val / RHS.Val;
      } else if (ValueLive) {
        PP.Diag(OpLoc, diag::err_pp_division_by_zero)
            << LHS.getRange() << RHS.getRange();
        return true;
      }
      break;

    case tok::star:
      if (Res.isSigned())
        Res = llvm::APSInt(LHS.Val.smul_ov(RHS.Val, Overflow), false);
      else
        Res = LHS.Val * RHS.Val;
      break;
    case tok::lessless: {
      if (LHS.isUnsigned())
        Res = LHS.Val.ushl_ov(RHS.Val, Overflow);
      else
        Res = llvm::APSInt(LHS.Val.sshl_ov(RHS.Val, Overflow), false);
      break;
    }
    case tok::greatergreater: {
      // Determine whether overflow is about to happen.
      unsigned ShAmt = static_cast<unsigned>(RHS.Val.getLimitedValue());
      if (ShAmt >= LHS.getBitWidth()) {
        Overflow = true;
        ShAmt = LHS.getBitWidth() - 1;
      }
      Res = LHS.Val >> ShAmt;
      break;
    }
    case tok::plus:
      if (LHS.isUnsigned())
        Res = LHS.Val + RHS.Val;
      else
        Res = llvm::APSInt(LHS.Val.sadd_ov(RHS.Val, Overflow), false);
      break;
    case tok::minus:
      if (LHS.isUnsigned())
        Res = LHS.Val - RHS.Val;
      else
        Res = llvm::APSInt(LHS.Val.ssub_ov(RHS.Val, Overflow), false);
      break;
    case tok::lessequal:
      Res = LHS.Val <= RHS.Val;
      Res.setIsUnsigned(false);
      break;
    case tok::less:
      Res = LHS.Val < RHS.Val;
      Res.setIsUnsigned(false);
      break;
    case tok::greaterequal:
      Res = LHS.Val >= RHS.Val;
      Res.setIsUnsigned(false);
      break;
    case tok::greater:
      Res = LHS.Val > RHS.Val;
      Res.setIsUnsigned(false);
      break;
    case tok::exclaimequal:
      Res = LHS.Val != RHS.Val;
      Res.setIsUnsigned(false);
      break;
    case tok::equalequal:
      Res = LHS.Val == RHS.Val;
      Res.setIsUnsigned(false);
      break;
    case tok::amp:
      Res = LHS.Val & RHS.Val;
      break;
    case tok::caret:
      Res = LHS.Val ^ RHS.Val;
      break;
    case tok::pipe:
      Res = LHS.Val | RHS.Val;
      break;
    case tok::ampamp:
      Res = (LHS.Val != 0 && RHS.Val != 0);
      Res.setIsUnsigned(false);
      break;
    case tok::pipepipe:
      Res = (LHS.Val != 0 || RHS.Val != 0);
      Res.setIsUnsigned(false);
      break;
    case tok::comma:
      if (!PP.getLangOpts().C99 || ValueLive)
        PP.Diag(OpLoc, diag::ext_pp_comma_expr)
            << LHS.getRange() << RHS.getRange();
      Res = RHS.Val;
      break;
    case tok::question: {
      if (PeekTok.isNot(tok::colon)) {
        PP.Diag(PeekTok.getLocation(), diag::err_expected)
            << tok::colon << LHS.getRange() << RHS.getRange();
        PP.Diag(OpLoc, diag::note_matching) << tok::question;
        return true;
      }
      PP.LexSkipComments(PeekTok);

      bool AfterColonLive = ValueLive && LHS.Val == 0;
      CondExprValue AfterColonVal(LHS.getBitWidth());
      MacroDefinedState DT;
      if (evaluateConditionAtom(AfterColonVal, PeekTok, DT, AfterColonLive, PP))
        return true;

      if (evaluateBinaryCondition(AfterColonVal, ThisPrec, PeekTok,
                                  AfterColonLive, IncludedUndefinedIds, PP))
        return true;

      Res = LHS.Val != 0 ? RHS.Val : AfterColonVal.Val;
      RHS.setEnd(AfterColonVal.getRange().getEnd());
      Res.setIsUnsigned(RHS.isUnsigned() || AfterColonVal.isUnsigned());
      PeekPrec = getDirectivePrecedence(PeekTok.getKind());
      break;
    }
    case tok::colon:
      PP.Diag(OpLoc, diag::err_pp_colon_without_question)
          << LHS.getRange() << RHS.getRange();
      return true;
    }

    if (Overflow && ValueLive)
      PP.Diag(OpLoc, diag::warn_pp_expr_overflow)
          << LHS.getRange() << RHS.getRange();

    LHS.Val = Res;
    LHS.setEnd(RHS.getRange().getEnd());
    RHS.setIdentifier(nullptr);
  }
}
} // namespace

// ===----------------------------------------------------------------------===
// Public API
// ===----------------------------------------------------------------------===

PrepEngine::CondEvalOutcome
PrepEngine::EvalCondExpr(IdentifierInfo *&IfNDefMacro) {
  SaveAndRestore PPDir(ParsingIfOrElifDirective, true);
  bool DisableMacroExpansionAtStartOfDirective = DisableMacroExpansion;
  DisableMacroExpansion = false;

  Token Tok;
  LexSkipComments(Tok);

  unsigned BitWidth = getTargetInfo().getIntMaxTWidth();

  CondExprValue ResVal(BitWidth);
  MacroDefinedState DT;
  SourceLocation ExprStartLoc = SourceMgr.getExpansionLoc(Tok.getLocation());
  if (LLVM_UNLIKELY(evaluateConditionAtom(ResVal, Tok, DT, true, *this))) {
    SourceRange ConditionRange = ExprStartLoc;
    if (Tok.isNot(tok::eod))
      ConditionRange = DiscardDirectiveLine();

    DisableMacroExpansion = DisableMacroExpansionAtStartOfDirective;

    // We cannot trust the source range from the value because there was a
    // parse error. Track the range manually -- the end of the directive is the
    // end of the condition range.
    return {false,
            DT.IncludedUndefinedIds,
            {ExprStartLoc, ConditionRange.getEnd()}};
  }

  // If we are at the end of the expression after just parsing a value, there
  // must be no (unparenthesized) binary operators involved, so we can exit
  // directly.
  if (Tok.is(tok::eod)) {
    // If the expression we parsed was of the form !defined(macro), return the
    // macro in IfNDefMacro.
    if (DT.State == MacroDefinedState::NotDefinedMacro)
      IfNDefMacro = DT.TheMacro;

    DisableMacroExpansion = DisableMacroExpansionAtStartOfDirective;
    return {ResVal.Val != 0, DT.IncludedUndefinedIds, ResVal.getRange()};
  }

  // Otherwise, we must have a binary operator (e.g. "#if 1 < 2"), so parse the
  // operator and the stuff after it.
  if (LLVM_UNLIKELY(
          evaluateBinaryCondition(ResVal, getDirectivePrecedence(tok::question),
                                  Tok, true, DT.IncludedUndefinedIds, *this))) {
    if (Tok.isNot(tok::eod))
      DiscardDirectiveLine();

    // Restore 'DisableMacroExpansion'.
    DisableMacroExpansion = DisableMacroExpansionAtStartOfDirective;
    return {false, DT.IncludedUndefinedIds, ResVal.getRange()};
  }

  // If we aren't at the tok::eod token, something bad happened, like an extra
  // ')' token.
  if (Tok.isNot(tok::eod)) {
    Diag(Tok, diag::err_pp_expected_eol);
    DiscardDirectiveLine();
  }

  DisableMacroExpansion = DisableMacroExpansionAtStartOfDirective;
  return {ResVal.Val != 0, DT.IncludedUndefinedIds, ResVal.getRange()};
}
