file(STRINGS "${INPUTS}" _archives)
foreach(_archive IN LISTS _archives)
  if(NOT EXISTS "${_archive}")
    message(FATAL_ERROR "Missing private frontend archive: ${_archive}")
  endif()
endforeach()
set(_temporary "${OUTPUT}.tmp")
get_filename_component(_output_dir "${OUTPUT}" DIRECTORY)
file(MAKE_DIRECTORY "${_output_dir}")
file(REMOVE "${_temporary}")
if(KIND STREQUAL "darwin")
  execute_process(COMMAND "${TOOL}" -static -o "${_temporary}" ${_archives}
    RESULT_VARIABLE _result)
elseif(KIND STREQUAL "msvc")
  set(_response "\"/OUT:${_temporary}\"\n")
  foreach(_archive IN LISTS _archives)
    string(APPEND _response "\"${_archive}\"\n")
  endforeach()
  file(WRITE "${OUTPUT}.rsp" "${_response}")
  execute_process(COMMAND "${TOOL}" /NOLOGO "@${OUTPUT}.rsp"
    RESULT_VARIABLE _result)
else()
  set(_mri "CREATE \"${_temporary}\"\n")
  foreach(_archive IN LISTS _archives)
    string(APPEND _mri "ADDLIB \"${_archive}\"\n")
  endforeach()
  string(APPEND _mri "SAVE\nEND\n")
  file(WRITE "${OUTPUT}.mri" "${_mri}")
  execute_process(COMMAND "${TOOL}" -M INPUT_FILE "${OUTPUT}.mri"
    RESULT_VARIABLE _result)
endif()
if(NOT _result EQUAL 0)
  file(REMOVE "${_temporary}")
  message(FATAL_ERROR "Failed to aggregate private frontend static libraries")
endif()
file(RENAME "${_temporary}" "${OUTPUT}")
