#!/usr/bin/env python3
"""Controlled llvm-readobj records for the private COFF fallback proof."""

import io
import subprocess
import sys
import unittest
from unittest import mock

sys.dont_write_bytecode = True
import CoffWeakAliases as coff


def symbol(name, storage=2, section=1, value=0, linked=None, search=1):
    storage_name = {2: "External", 3: "Static", 6: "Label", 105: "WeakExternal"}[storage]
    section_name = ".text" if section > 0 else "IMAGE_SYM_UNDEFINED"
    result = ("  Symbol {\n"
              f"    Name: {name}\n"
              f"    Value: {value}\n"
              f"    Section: {section_name} ({section})\n"
              "    BaseType: Null (0x0)\n"
              "    ComplexType: Function (0x2)\n"
              f"    StorageClass: {storage_name} (0x{storage:X})\n"
              f"    AuxSymbolCount: {int(linked is not None)}\n")
    if linked is not None:
        search_name = {1: "NoLibrary", 2: "Library", 3: "Alias", 4: "AntiDependency"}[search]
        result += ("    AuxWeakExternal {\n"
                   f"      Linked: {linked[0]} ({linked[1]})\n"
                   f"      Search: {search_name} (0x{search:X})\n"
                   "    }\n")
    return result + "  }\n"


def member(*symbols, name="private.lib(member.obj)"):
    return (f"File: {name}\nFormat: COFF-x86-64\nArch: x86_64\n"
            "AddressSize: 64bit\nSymbols [\n" + "".join(symbols) + "]\n")


def weak(name="private_alias", target="private_body", index=0, search=1):
    return symbol(name, storage=105, section=0, linked=(target, index), search=search)


class CoffWeakAliasesTests(unittest.TestCase):
    # Independent identities from the pinned Setup SDK and the approved
    # private-name contract, not generated by the production policy helper.
    guid_names = (
        ("_GUID_00000000_0000_0000_c000_000000000046", "neverc_cpp0000000000000000c000000000000046"),
        ("_GUID_177f0c4a_1cd3_4de7_a32c_71dbbb9fa36d", "neverc_cpp177f0c4a1cd34de7a32c71dbbb9fa36d"),
        ("_GUID_42843719_db4c_46c2_8e7c_64f1816efd5b", "neverc_cpp42843719db4c46c28e7c64f1816efd5b"),
        ("_GUID_26aab78c_4a60_49d6_af3b_3c35bc93365d", "neverc_cpp26aab78c4a6049d6af3b3c35bc93365d"),
        ("_GUID_42b21b78_6192_463e_87bf_d577838f1d5c", "neverc_cpp42b21b786192463e87bfd577838f1d5c"),
    )
    old_guid_template = (
        "?GetIID@?$_com_IIID@UISetupConfiguration2@@$1?"
        "_GUID_26aab78c_4a60_49d6_af3b_3c35bc93365d@@3U__s_GUID@@B@@SAAEBU_GUID@@XZ")
    private_guid_template = (
        "?GetIID@?$_com_IIID@UISetupConfiguration2@@$1?"
        "neverc_cpp26aab78c4a6049d6af3b3c35bc93365d@@3U__s_GUID@@B@@SAAEBU_GUID@@XZ")
    private_guid_metadata = (
        "$pdata$??1?$_com_ptr_t@V?$_com_IIID@UISetupConfiguration2@@$1?"
        "neverc_cpp26aab78c4a6049d6af3b3c35bc93365d@@3U__s_GUID@@B@@@@QEAA@XZ")

    def parse(self, text, definitions=("private_body",), private=("private_alias",)):
        return coff.parse_resolved_aliases(io.StringIO(text), set(definitions), set(private))

    def test_old_setup_guid_external_reference_and_local_names_are_rejected(self):
        for old, _ in self.guid_names:
            for storage, section in ((2, 1), (2, 0), (3, 1)):
                with self.subTest(name=old, storage=storage, section=section):
                    with self.assertRaisesRegex(ValueError, "unisolated Setup GUID symbol: " + old):
                        self.parse(member(symbol(old, storage=storage, section=section)),
                                   definitions=(old,), private=())

    def test_old_setup_guid_template_and_unknown_grammar_are_rejected(self):
        for name in (self.old_guid_template, "unrecognized$" + self.guid_names[0][0]):
            with self.subTest(name=name):
                with self.assertRaisesRegex(ValueError, "unisolated Setup GUID symbol:"):
                    self.parse(member(symbol(name)), definitions=(name,), private=())

    def test_old_setup_guid_weak_symbol_name_is_rejected(self):
        for old, _ in self.guid_names:
            with self.subTest(name=old):
                with self.assertRaisesRegex(ValueError, "unisolated Setup GUID symbol: " + old):
                    self.parse(member(symbol("private_body"), weak(name=old)),
                               definitions=("private_body", old), private=())

    def test_old_setup_guid_aux_name_is_checked_before_tag_index_resolution(self):
        names = [old for old, _ in self.guid_names] + [self.old_guid_template]
        for old in names:
            with self.subTest(name=old):
                # The ordinary primary record cannot hide a forbidden Linked
                # name, even when the TagIndex/name pair itself is inconsistent.
                text = member(symbol("ordinary"), weak(target=old))
                with self.assertRaisesRegex(ValueError, "unisolated Setup GUID symbol:"):
                    self.parse(text, definitions=("ordinary",), private=())

    def test_old_setup_guid_fallback_is_not_hidden_by_an_overriding_definition(self):
        for old, _ in self.guid_names:
            with self.subTest(name=old):
                text = (member(symbol(old, section=0), weak(target=old),
                               name="private.lib(weak.obj)") +
                        member(symbol("private_alias"), name="private.lib(body.obj)"))
                with self.assertRaisesRegex(ValueError, "unisolated Setup GUID symbol: " + old):
                    self.parse(text, definitions=("private_alias",), private=())

    def test_old_setup_guid_multihop_local_target_is_rejected(self):
        for old, _ in self.guid_names:
            with self.subTest(name=old):
                text = member(symbol(old, storage=3),
                              weak(name="middle", target=old, index=0, search=3),
                              weak(target="middle", index=1))
                with self.assertRaisesRegex(ValueError, "unisolated Setup GUID symbol: " + old):
                    self.parse(text, definitions=("middle", "private_alias"), private=())

    def test_private_setup_guid_plain_reference_requires_actual_definition(self):
        names = [new for _, new in self.guid_names] + [self.private_guid_template]
        for name in names:
            for definitions in ((), (name,)):
                with self.subTest(name=name, nm_definitions=definitions):
                    with self.assertRaisesRegex(ValueError, "unresolved private dependency:"):
                        self.parse(member(symbol(name, section=0)),
                                   definitions=definitions, private=())

    def test_private_setup_guid_definition_satisfies_another_member_reference(self):
        names = [new for _, new in self.guid_names] + [self.private_guid_template]
        for name in names:
            with self.subTest(name=name):
                text = (member(symbol(name, section=0), name="private.lib(use.obj)") +
                        member(symbol(name), name="private.lib(body.obj)"))
                self.assertEqual(self.parse(text, definitions=(name,), private=()), set())

    def test_private_setup_guid_static_definition_cannot_satisfy_global_reference(self):
        for _, name in self.guid_names:
            with self.subTest(name=name):
                text = (member(symbol(name, section=0), name="private.lib(use.obj)") +
                        member(symbol(name, storage=3), name="private.lib(local.obj)"))
                with self.assertRaisesRegex(ValueError, "unresolved private dependency: " + name):
                    self.parse(text, definitions=(name,), private=())

    def test_private_setup_guid_local_definition_is_not_a_global_requirement(self):
        for _, name in self.guid_names:
            with self.subTest(name=name):
                self.assertEqual(self.parse(member(symbol(name, storage=3)),
                                            definitions=(), private=()), set())

    def test_metadata_definition_does_not_seed_external_closure(self):
        name = self.private_guid_metadata
        record = symbol(name, storage=3).replace("Section: .text (1)", "Section: .pdata (1)")
        record = record.replace("ComplexType: Function (0x2)", "ComplexType: Null (0x0)")
        # Even an erroneous caller inventory must not promote this local
        # metadata name into a resolved external identity.
        self.assertEqual(self.parse(member(record), definitions=(name,), private=(name,)), set())
        external = self.guid_names[0][1]
        text = member(record, name="private.lib(metadata.obj)") + member(
            symbol(external, section=0), name="private.lib(use.obj)")
        with self.assertRaisesRegex(ValueError, "unresolved private dependency: " + external):
            self.parse(text, definitions=(name, external), private=(external,))

    def test_metadata_requires_defined_static_nonaux_storage(self):
        name = self.private_guid_metadata
        for storage, section in ((2, 1), (2, 0), (3, 0), (6, 1)):
            with self.subTest(storage=storage, section=section):
                with self.assertRaisesRegex(ValueError, "Invalid private Setup GUID metadata storage"):
                    self.parse(member(symbol(name, storage=storage, section=section)),
                               definitions=(name,), private=())
        with self.assertRaisesRegex(ValueError, "Invalid private Setup GUID metadata storage"):
            self.parse(member(symbol("private_body"), weak(name=name)), private=())

    def test_metadata_aux_record_is_not_an_observed_identity_shape(self):
        name = self.private_guid_metadata
        record = symbol(name, storage=3).replace("AuxSymbolCount: 0", "AuxSymbolCount: 1")
        aux = ("    AuxSectionDef {\n      Length: 8\n      RelocationCount: 1\n"
               "      LineNumberCount: 0\n      Checksum: 0x0\n      Number: 1\n"
               "      Selection: Associative (0x5)\n      AssocSection: .text (1)\n    }\n")
        record = record[:-4] + aux + "  }\n"
        with self.assertRaisesRegex(ValueError, "Invalid private Setup GUID metadata storage"):
            self.parse(member(record), definitions=(), private=())

    def test_static_metadata_cannot_mask_same_name_external_reference(self):
        name = self.private_guid_metadata
        text = (member(symbol(name, storage=3), name="private.lib(metadata.obj)") +
                member(symbol(name, section=0), name="private.lib(use.obj)"))
        with self.assertRaisesRegex(ValueError, "Invalid private Setup GUID metadata storage"):
            self.parse(text, definitions=(name,), private=(name,))

    def test_private_guid_fallback_cannot_use_metadata_as_its_terminal(self):
        alias = self.guid_names[0][1]
        text = member(symbol(self.private_guid_metadata, storage=3),
                      weak(name=alias, target=self.private_guid_metadata))
        with self.assertRaisesRegex(ValueError, "COFF fallback cannot use private Setup GUID metadata"):
            self.parse(text, definitions=(alias,), private=(alias,))

    def test_intermediate_alias_cannot_promote_metadata_to_private_guid_terminal(self):
        alias = self.guid_names[0][1]
        text = member(symbol(self.private_guid_metadata, storage=3),
                      weak(name="middle", target=self.private_guid_metadata),
                      weak(name=alias, target="middle", index=1))
        with self.assertRaisesRegex(ValueError, "COFF fallback cannot use private Setup GUID metadata"):
            self.parse(text, definitions=(alias, "middle"), private=(alias,))

    def test_unobserved_metadata_combination_is_rejected(self):
        # _com_IIID::GetIID has no observed $pdata$ metadata; unlike its
        # _com_ptr_t wrapper it cannot acquire support from the prefix alone.
        for name in ("$pdata$" + self.private_guid_template,
                     "$future$" + self.private_guid_metadata[len("$pdata$"):]):
            with self.subTest(name=name):
                with self.assertRaisesRegex(ValueError, "Unsupported private Setup GUID symbol grammar"):
                    self.parse(member(symbol(name, storage=3)), definitions=(), private=())

    def test_original_metadata_identity_is_rejected(self):
        old = ("$pdata$??1?$_com_ptr_t@V?$_com_IIID@UISetupConfiguration2@@$1?"
               "_GUID_26aab78c_4a60_49d6_af3b_3c35bc93365d@@3U__s_GUID@@B@@@@QEAA@XZ")
        with self.assertRaisesRegex(ValueError, "unisolated Setup GUID symbol:"):
            self.parse(member(symbol(old, storage=3)), definitions=(), private=())

    def test_unrelated_native_labels_remain_accepted(self):
        for name in ("$LN4", "__swt"):
            with self.subTest(name=name):
                self.assertEqual(self.parse(member(symbol(name, storage=6)),
                                            definitions=(), private=()), set())

    def test_private_setup_guid_undefined_static_record_is_rejected(self):
        name = self.guid_names[0][1]
        with self.assertRaisesRegex(ValueError, "no external or local COFF definition"):
            self.parse(member(symbol(name, storage=3, section=0)),
                       definitions=(), private=())

    def test_private_setup_guid_weak_alias_requires_private_terminal_for_all_modes(self):
        for _, name in self.guid_names:
            for search in (1, 2, 3):
                with self.subTest(name=name, search=search):
                    text = member(symbol("host_only", section=0),
                                  weak(name=name, target="host_only", search=search))
                    with self.assertRaisesRegex(ValueError, "unresolved private dependency: " + name):
                        self.parse(text, definitions=(name, "host_only"), private=())

    def test_private_setup_guid_weak_alias_accepts_its_own_local_terminal(self):
        for _, name in self.guid_names:
            with self.subTest(name=name):
                text = member(symbol("local_body", storage=3),
                              weak(name=name, target="local_body"))
                self.assertEqual(self.parse(text, definitions=(name,), private=()), {name})

    def test_private_setup_guid_local_target_does_not_require_global_definition(self):
        names = [new for _, new in self.guid_names] + [self.private_guid_template]
        for name in names:
            with self.subTest(name=name):
                text = member(symbol(name, storage=3), weak(target=name))
                self.assertEqual(self.parse(text, definitions=(), private=()),
                                 {"private_alias"})

    def test_private_setup_guid_target_is_required_even_for_optional_alias(self):
        name = self.guid_names[0][1]
        text = member(symbol(name, section=0), weak(name="platform_optional", target=name))
        with self.assertRaisesRegex(ValueError, "unresolved private dependency: " + name):
            self.parse(text, definitions=(), private=())
        text += member(symbol(name), name="private.lib(body.obj)")
        self.assertEqual(self.parse(text, definitions=(name,), private=()),
                         {"platform_optional"})

    def test_private_setup_guid_multihop_target_cannot_borrow_host(self):
        name = self.guid_names[0][1]
        text = member(symbol(name, section=0),
                      weak(name="middle", target=name, index=0, search=3),
                      weak(target="middle", index=1))
        with self.assertRaisesRegex(ValueError, "unresolved private dependency: " + name):
            self.parse(text, definitions=(name, "middle", "private_alias"), private=())
        text += member(symbol(name), name="private.lib(body.obj)")
        self.assertEqual(self.parse(text, definitions=(name,), private=()),
                         {"middle", "private_alias"})

    def test_private_setup_guid_actual_definition_still_overrides_weak_fallback(self):
        name = self.guid_names[0][1]
        text = (member(symbol("missing", section=0), weak(name=name, target="missing"),
                       name="private.lib(weak.obj)") +
                member(symbol(name), name="private.lib(body.obj)"))
        self.assertEqual(self.parse(text, definitions=(name,), private=()), {name})

    def test_private_setup_guid_alias_cycle_fails_without_caller_private_names(self):
        name = self.guid_names[0][1]
        text = member(weak(name=name, target="middle", index=2, search=3),
                      weak(name="middle", target=name, index=0, search=3))
        with self.assertRaisesRegex(ValueError, "unresolved private dependency: " + name):
            self.parse(text, definitions=(name, "middle"), private=())

    def test_unknown_selected_guid_grammar_failure_is_not_swallowed(self):
        for _, name in self.guid_names:
            unknown = "unrecognized$" + name
            for text in (member(symbol(unknown)),
                         member(symbol("ordinary"), weak(target=unknown))):
                with self.subTest(name=unknown, linked="Linked:" in text):
                    with self.assertRaisesRegex(ValueError, "Unsupported private Setup GUID"):
                        self.parse(text, definitions=(unknown, "ordinary"), private=())

    def test_unrelated_guid_identity_is_not_rejected(self):
        name = "_GUID_00000000_0000_0000_c000_000000000047"
        self.assertEqual(self.parse(member(symbol(name)), definitions=(name,), private=()), set())

    def test_all_supported_search_modes_require_an_actual_target(self):
        for search in (1, 2, 3):
            with self.subTest(search=search):
                self.assertEqual(self.parse(member(symbol("private_body"), weak(search=search))),
                                 {"private_alias"})

    def test_exact_runtime_fallback_requires_every_edge_and_real_target(self):
        wrapper = "?__global_delete@@YAXPEAX_K@Z"
        fallback = "?__empty_global_delete@@YAXPEAX_K@Z"

        def exact(text, definitions=(fallback,)):
            return coff.parse_resolved_aliases(
                io.StringIO(text), set(definitions), {wrapper},
                expected_fallbacks={wrapper: fallback})

        valid = member(symbol(fallback), weak(name=wrapper, target=fallback))
        self.assertIn(wrapper, exact(valid))
        split = (member(symbol(fallback, section=0), weak(name=wrapper, target=fallback),
                        name="private.lib(use.obj)") +
                 member(symbol(fallback), name="private.lib(body.obj)"))
        self.assertIn(wrapper, exact(split))
        invalid = (
            (member(symbol(fallback)), (fallback,)),
            (member(symbol(fallback, section=0), weak(name=wrapper, target=fallback)), (fallback,)),
            (member(symbol(fallback, storage=3), weak(name=wrapper, target=fallback)), (fallback,)),
            (member(symbol("wrong"), weak(name=wrapper, target="wrong")), ("wrong", fallback)),
            (member(symbol(fallback), weak(name=wrapper, target=fallback)), ()),
            (member(symbol("body"), weak(name=fallback, target="body"),
                    weak(name=wrapper, target=fallback, index=1)), (fallback, "body")),
            (member(weak(name=fallback, target=wrapper, index=2),
                    weak(name=wrapper, target=fallback)), (fallback, wrapper)),
            (valid + member(symbol("wrong"), weak(name=wrapper, target="wrong"),
                            name="private.lib(other.obj)"), (fallback, "wrong")),
        )
        for text, definitions in invalid:
            with self.subTest(text=text):
                with self.assertRaises(ValueError):
                    exact(text, definitions)

    def test_global_fallback_definition_may_be_in_another_member(self):
        text = (member(symbol("private_body", section=0), weak(), name="private.lib(a.obj)") +
                member(symbol("private_body"), name="private.lib(b.obj)"))
        self.assertEqual(self.parse(text), {"private_alias"})

    def test_plain_reference_in_another_member_does_not_hide_the_alias(self):
        text = (member(symbol("private_alias", section=0), name="private.lib(use.obj)") +
                member(symbol("private_body"), weak(), name="private.lib(alias.obj)"))
        self.assertEqual(self.parse(text), {"private_alias"})

    def test_local_fallback_is_proved_by_its_own_member_definition(self):
        self.assertEqual(self.parse(member(symbol("local_body", storage=3),
                                           weak(target="local_body")), definitions=()),
                         {"private_alias"})

    def test_other_member_static_name_cannot_satisfy_a_global_fallback(self):
        text = (member(symbol("private_body", section=0), weak(), name="private.lib(a.obj)") +
                member(symbol("private_body", storage=3), name="private.lib(b.obj)"))
        with self.assertRaisesRegex(ValueError, "no actual private definition"):
            self.parse(text)

    def test_nm_definition_name_is_not_enough_without_real_coff_definition(self):
        with self.assertRaisesRegex(ValueError, "no actual private definition"):
            self.parse(member(symbol("private_body", section=0), weak()))

    def test_host_or_standard_named_target_is_not_a_terminal_escape(self):
        for target in ("host_function", "?function@std@@YAXXZ"):
            with self.subTest(target=target):
                with self.assertRaisesRegex(ValueError, "no actual private definition"):
                    self.parse(member(symbol(target, section=0), weak(target=target)),
                               definitions=(target,))

    def test_nm_uppercase_weak_alias_is_not_a_definition_seed(self):
        text = member(weak(name="private_alias", target="other_alias", index=2, search=3),
                      weak(name="other_alias", target="private_alias", index=0, search=3))
        with self.assertRaisesRegex(ValueError, "cycle"):
            self.parse(text, definitions=("private_alias", "other_alias"))

    def test_separate_actual_definition_overrides_a_weak_fallback(self):
        text = (member(symbol("missing", section=0), weak(target="missing"),
                       name="private.lib(weak.obj)") +
                member(symbol("private_alias"), name="private.lib(body.obj)"))
        self.assertEqual(self.parse(text, definitions=("private_alias",)),
                         {"private_alias"})

    def test_multihop_fallback_is_proved_to_its_actual_terminal(self):
        text = member(symbol("private_body"),
                      weak(name="middle", index=0, search=3),
                      weak(index=1, target="middle"))
        self.assertEqual(self.parse(text, definitions=("private_body", "middle")),
                         {"middle", "private_alias"})

    def test_tag_index_must_point_to_primary_symbol_with_the_same_name(self):
        for target, index in (("private_body", 999), ("wrong_name", 0),
                              ("private_alias", 2)):
            with self.subTest(target=target, index=index):
                with self.assertRaisesRegex(ValueError, "TagIndex/name"):
                    self.parse(member(symbol("private_body"), weak(target=target, index=index)))

    def test_unknown_or_anti_dependency_search_is_not_accepted(self):
        text = member(symbol("private_body"), weak(search=4))
        with self.assertRaisesRegex(ValueError, "Unsupported COFF weak search"):
            self.parse(text)
        with self.assertRaisesRegex(ValueError, "Unsupported COFF weak search"):
            self.parse(text.replace("AntiDependency (0x4)", "Unknown (0xFF)"))

    def test_ordinary_undefined_storage_cannot_be_treated_as_a_weak_alias(self):
        text = member(symbol("private_body"), symbol(
            "private_alias", storage=2, section=0, linked=("private_body", 0)))
        with self.assertRaisesRegex(ValueError, "Malformed COFF weak external"):
            self.parse(text)

    def test_conflicting_fallback_edges_are_rejected_even_if_both_bodies_exist(self):
        text = (member(symbol("one"), weak(target="one"), name="private.lib(a.obj)") +
                member(symbol("two"), weak(target="two"), name="private.lib(b.obj)"))
        with self.assertRaisesRegex(ValueError, "Conflicting COFF fallback"):
            self.parse(text, definitions=("one", "two"))

    def test_unresolved_optional_nonprivate_alias_is_not_falsely_proved(self):
        text = member(symbol("platform_optional", section=0),
                      weak(name="platform_weak", target="platform_optional"))
        self.assertEqual(self.parse(text, definitions=(), private=()), set())

    def test_malformed_truncated_or_unknown_schema_fails_closed(self):
        valid = member(symbol("private_body"), weak())
        for text in ("", valid[:-2], valid.replace("Symbols [", "Symbols {"),
                     valid.replace("    Name: private_body", "    Unknown: private_body"),
                     valid.replace("      Linked:", "     Linked:"),
                     valid.replace("    Name: private_body\n", "    Name: private_body\n    Name: duplicate\n"),
                     valid.replace("private_body", "bad\x00name")):
            with self.subTest(text=text[:80]):
                with self.assertRaises(ValueError):
                    self.parse(text)

    def test_all_ascii_control_characters_are_rejected_inside_a_field(self):
        valid = member(symbol("private_body"), weak())
        self.assertEqual(self.parse(valid), {"private_alias"})
        valid_lines = valid.splitlines(keepends=True)
        field_index = valid_lines.index("    Name: private_body\n")
        for codepoint in (*range(32), 127):
            with self.subTest(codepoint=codepoint):
                lines = list(valid_lines)
                # Insert after splitting so embedded CR/LF reaches the parser's
                # control check, independently of the input iterator's framing.
                lines[field_index] = f"    Name: private{chr(codepoint)}body\n"
                with self.assertRaisesRegex(
                        ValueError, "^Control character in llvm-readobj symbol inventory$"):
                    coff.parse_resolved_aliases(
                        iter(lines), {"private_body"}, {"private_alias"})

    def test_printable_and_non_ascii_symbol_characters_remain_accepted(self):
        for character in (" ", "~", "\x80", "é", "中", "\u2028", "\u2029"):
            with self.subTest(character=character):
                name = "private" + character + "body"
                self.assertEqual(
                    self.parse(member(symbol(name), weak(target=name)), definitions=(name,)),
                    {"private_alias"})

    def test_crlf_symbol_inventory_preserves_alias_resolution(self):
        text = member(symbol("private_body"), weak()).replace("\n", "\r\n")
        self.assertEqual(self.parse(text), {"private_alias"})
        self.assertEqual(self.inspect(text), {"private_alias"})

    def test_line_and_member_inventory_limits_are_bounded(self):
        with mock.patch.object(coff, "MAX_LINE", 16):
            with self.assertRaisesRegex(ValueError, "line exceeds"):
                self.parse(member(symbol("private_body"), weak()))
        with mock.patch.object(coff, "MAX_SYMBOLS_PER_MEMBER", 1):
            with self.assertRaisesRegex(ValueError, "member symbol inventory"):
                self.parse(member(symbol("private_body"), weak()))

    def test_fallback_depth_is_bounded_before_python_recursion_limit(self):
        text = member(symbol("private_body"),
                      weak(name="z_middle", index=0),
                      weak(index=1, target="z_middle"))
        with mock.patch.object(coff, "MAX_CHAIN", 1):
            with self.assertRaisesRegex(ValueError, "chain exceeds"):
                self.parse(text)

    def inspect(self, text, status=0, diagnostic=b""):
        process = mock.Mock()
        process.wait.return_value = status
        process.poll.return_value = status

        def launch(arguments, stdout, stderr):
            self.assertEqual(arguments, ["private-readobj", "--symbols", "--no-demangle", "private.lib"])
            stdout.write(text.encode("utf-8"))
            stdout.flush()
            stderr.write(diagnostic)
            stderr.flush()
            return process

        with mock.patch.object(coff.subprocess, "Popen", side_effect=launch):
            return coff.read_resolved_aliases("private-readobj", "private.lib",
                                              {"private_body"}, {"private_alias"})

    def test_tool_output_is_parsed_from_bounded_temporary_files(self):
        self.assertEqual(self.inspect(member(symbol("private_body"), weak())), {"private_alias"})

    def test_tool_errors_and_warnings_cannot_silently_omit_members(self):
        text = member(symbol("private_body"), weak())
        for status, diagnostic in ((1, b"corrupt object"), (0, b"unsupported member")):
            with self.subTest(status=status):
                with self.assertRaisesRegex(ValueError, "llvm-readobj inspection failed"):
                    self.inspect(text, status, diagnostic)

    def test_tool_output_size_is_limited(self):
        with mock.patch.object(coff, "MAX_OUTPUT", 4):
            with self.assertRaisesRegex(ValueError, "output exceeds"):
                self.inspect(member(symbol("private_body"), weak()))

    def test_timeout_kills_and_reaps_the_reader(self):
        process = mock.Mock()
        process.poll.return_value = None
        process.wait.return_value = 0
        with mock.patch.object(coff.subprocess, "Popen", return_value=process), \
                mock.patch.object(coff.time, "monotonic", side_effect=[0, coff.READ_TIMEOUT + 1]):
            with self.assertRaisesRegex(ValueError, "timed out"):
                coff.read_resolved_aliases("private-readobj", "private.lib", set())
        process.kill.assert_called_once_with()
        process.wait.assert_called_once_with()


if __name__ == "__main__":
    unittest.main()
