#!/usr/bin/env python3
"""Generate html_entities.h from the Go standard library html/entity.go."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


SINGLE = re.compile(
    r'^\s*"([A-Za-z0-9]+;?)":\s+\'\\[uU]([0-9A-Fa-f]{4,8})\','
)
DOUBLE = re.compile(
    r'^\s*"([A-Za-z0-9]+;?)":\s+\{\'\\[uU]([0-9A-Fa-f]{4,8})\','
    r'\s+\'\\[uU]([0-9A-Fa-f]{4,8})\'\},'
)


def parse(source: str) -> dict[str, tuple[int, int]]:
    entries: dict[str, tuple[int, int]] = {}
    for line in source.splitlines():
        match = DOUBLE.match(line)
        if match:
            entries[match.group(1)] = (
                int(match.group(2), 16),
                int(match.group(3), 16),
            )
            continue
        match = SINGLE.match(line)
        if match:
            entries[match.group(1)] = (int(match.group(2), 16), 0)
    if len(entries) < 2200:
        raise ValueError(f"expected the full Go entity table, found {len(entries)}")
    return entries


def render(entries: dict[str, tuple[int, int]]) -> str:
    lines = [
        "/* Code generated by gen_entities.py from Go's html/entity.go; DO NOT EDIT.",
        " * The source data and generator-derived table are covered by Go's BSD license.",
        " * Copyright 2009 The Go Authors. All rights reserved. */",
        "static const html_named_entity_t html_named_entities[] = {",
    ]
    for name, (first, second) in sorted(entries.items()):
        lines.append(
            f'    {{"{name}", {len(name)}, 0x{first:08X}u, 0x{second:08X}u}},'
        )
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    entries = parse(args.source.read_text(encoding="utf-8"))
    args.output.write_text(render(entries), encoding="utf-8")


if __name__ == "__main__":
    main()
