#!/usr/bin/env python3
"""Generate the compiler's exact std dot-method dispatch table."""

import argparse
import json
import re
import sys
from pathlib import Path


REPO = Path(__file__).resolve().parents[2]
DEFAULT_MANIFEST = REPO / "std" / "manifest.json"
DEFAULT_OUTPUT = (
    REPO
    / "neverc"
    / "include"
    / "neverc"
    / "Foundation"
    / "Std"
    / "StdModuleMethods.def"
)
IDENTIFIER = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def module_marker(module_key, module):
    return module.get("dot_marker", module_key.rsplit("/", 1)[-1])


def collect_entries(manifest):
    modules = manifest.get("modules")
    if not isinstance(modules, dict):
        raise ValueError("manifest must contain an object-valued 'modules'")

    entries = []
    seen = {}
    for module_key, module in modules.items():
        if not isinstance(module, dict):
            raise ValueError(f"module '{module_key}' must be an object")
        marker = module_marker(module_key, module)
        if not isinstance(marker, str) or not IDENTIFIER.fullmatch(marker):
            raise ValueError(
                f"module '{module_key}' has invalid dot marker {marker!r}"
            )
        symbols = module.get("symbols", {})
        methods = module.get("dot_methods", {})
        if not isinstance(symbols, dict) or not isinstance(methods, dict):
            raise ValueError(
                f"module '{module_key}' symbols/dot_methods must be objects"
            )
        for method, target in methods.items():
            if not isinstance(method, str) or not IDENTIFIER.fullmatch(method):
                raise ValueError(
                    f"module '{module_key}' has invalid dot method {method!r}"
                )
            if not isinstance(target, str) or not IDENTIFIER.fullmatch(target):
                raise ValueError(
                    f"module '{module_key}' method '{method}' has invalid "
                    f"target {target!r}"
                )
            if target not in symbols:
                raise ValueError(
                    f"module '{module_key}' method '{method}' targets "
                    f"unregistered symbol '{target}'"
                )
            key = (marker, method)
            if key in seen:
                raise ValueError(
                    f"dot method '{marker}.{method}' is declared by both "
                    f"'{seen[key]}' and '{module_key}'"
                )
            seen[key] = module_key
            entries.append((marker, method, target))
    entries.sort()
    return entries


def render(manifest):
    lines = [
        "// Generated by utils/lint/gen_std_module_methods.py from "
        "std/manifest.json.",
        "// Do not edit this file by hand.",
        "#ifndef STD_MODULE_METHOD",
        '#error "define STD_MODULE_METHOD(marker, method, target) before '
        'including this file"',
        "#endif",
        "",
    ]
    lines.extend(
        f"STD_MODULE_METHOD({marker}, {method}, {target})"
        for marker, method, target in collect_entries(manifest)
    )
    lines.extend(["", "#undef STD_MODULE_METHOD", ""])
    return "\n".join(lines)


def main(argv=None):
    parser = argparse.ArgumentParser()
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--write", action="store_true")
    args = parser.parse_args(argv)

    try:
        with args.manifest.open(encoding="utf-8") as source:
            generated = render(json.load(source))
    except (OSError, json.JSONDecodeError, ValueError) as error:
        print(f"std dot-method generation failed: {error}", file=sys.stderr)
        return 1

    if args.write:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(generated, encoding="utf-8")
        return 0

    try:
        current = args.output.read_text(encoding="utf-8")
    except OSError:
        current = None
    if current != generated:
        print(
            "std dot-method table is stale; run "
            "python3 utils/lint/gen_std_module_methods.py --write",
            file=sys.stderr,
        )
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
