#!/usr/bin/env python3
"""Compile the NVK kernel runtime to a single LLVM bitcode module and
embed it as a C header.

Usage:
    python3 build_nvk_kernel_bitcode.py <neverc> <runtime_dir> -o <output.h>

Creates a unity source that #include's every .c file under runtime_dir/src/,
compiles it with neverc into one aarch64 bitcode module, and emits a header
with the bitcode embedded as ``static const unsigned char kNvkKernelBC[]``.

The NvkKernelRuntimeLinkerPass then links this single pre-merged module into
each user TU at compile time — no runtime merge step needed.
"""

import argparse
import glob
import os
import subprocess
import sys
import tempfile


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("neverc", help="Path to neverc compiler binary")
    parser.add_argument("runtime_dir",
                        help="Path to runtime/android/kernel directory")
    parser.add_argument("-o", "--output", required=True,
                        help="Output .h header file")
    args = parser.parse_args()

    src_dir = os.path.join(args.runtime_dir, "src")
    inc_kern = os.path.join(args.runtime_dir, "arm64", "include")
    inc_nvk = os.path.join(args.runtime_dir, "include")

    sources = sorted(glob.glob(os.path.join(src_dir, "*.c")))
    sources = [s for s in sources
               if os.path.basename(s) != "nvk_runtime_bc.c"]

    if not sources:
        print(f"error: no .c files found in {src_dir}", file=sys.stderr)
        sys.exit(1)

    for d in (inc_kern, inc_nvk):
        if not os.path.isdir(d):
            print(f"error: include dir not found: {d}", file=sys.stderr)
            sys.exit(1)

    os.makedirs(os.path.dirname(args.output) or ".", exist_ok=True)

    src_dir_abs = os.path.abspath(src_dir)
    inc_kern_abs = os.path.abspath(inc_kern)
    inc_nvk_abs = os.path.abspath(inc_nvk)

    with tempfile.TemporaryDirectory(prefix="neverc_nvk_bc_") as tmpdir:
        unity_src = os.path.join(tmpdir, "nvk_kernel_unity.c")
        with open(unity_src, "w") as f:
            for src in sources:
                f.write(f'#include "{os.path.abspath(src)}"\n')

        bc_path = os.path.join(tmpdir, "nvk_kernel_runtime.bc")

        cmd = [
            args.neverc,
            "-c", "-emit-llvm", "-O0",
            "-gline-tables-only",
            "-fno-lto",
            "--target=aarch64-linux-gnu",
            "-ffreestanding", "-std=gnu11",
            "-D__KERNEL__", "-DMODULE", "-D_NEVERC_KRT_IMPL",
            f"-I{inc_kern}",
            f"-I{inc_nvk}",
            f"-fdebug-prefix-map={src_dir_abs}=runtime/android/kernel/src",
            f"-fdebug-prefix-map={inc_kern_abs}=runtime/android/kernel/arm64/include",
            f"-fdebug-prefix-map={inc_nvk_abs}=runtime/android/kernel/include",
            f"-fdebug-prefix-map={tmpdir}=runtime/android/kernel",
            "-w",
            unity_src, "-o", bc_path,
        ]
        print(f"  [bc] unity ({len(sources)} sources)", file=sys.stderr)
        try:
            subprocess.check_call(cmd)
        except subprocess.CalledProcessError as e:
            print(f"error: unity compilation failed (exit {e.returncode})",
                  file=sys.stderr)
            sys.exit(1)

        with open(bc_path, "rb") as f:
            bc_data = f.read()

    lines = []
    lines.append("/* Auto-generated by build_nvk_kernel_bitcode.py — DO NOT EDIT. */")
    lines.append("")
    lines.append("static const unsigned char kNvkKernelBC[] = {")
    for i in range(0, len(bc_data), 16):
        chunk = bc_data[i:i + 16]
        hex_vals = ", ".join(f"0x{b:02x}" for b in chunk)
        lines.append(f"  {hex_vals},")
    lines.append("};")
    lines.append("")
    lines.append(f"static const unsigned int kNvkKernelBCLen = sizeof(kNvkKernelBC);")
    lines.append("")

    with open(args.output, "w") as f:
        f.write("\n".join(lines))

    print(f"build_nvk_kernel_bitcode: {len(sources)} sources -> "
          f"{len(bc_data)} bytes -> {args.output}", file=sys.stderr)


if __name__ == "__main__":
    main()
