#!/usr/bin/env python3
"""Extract extern function declarations from BuiltinString prelude .inc files.

Run at CMake build time to generate the thin header's extern declaration
block.  Reads all .inc fragments under BuiltinStringPrelude/, strips the
R"prelude(...)prelude" wrapper, then uses regex to extract every
`static [__inline__] TYPE FUNCNAME(PARAMS)` signature and emits
`extern TYPE FUNCNAME(PARAMS);` lines.

Functions that must stay inline in the thin header (too small / used by
Sema directly) are excluded from the extern list.

Usage:
    python3 gen_thin_header.py <prelude_dir> -o <output.inc>

<prelude_dir> is the directory containing Type.inc, Allocation.inc, etc.
<output.inc>  receives the generated extern declarations.
"""

import argparse
import os
import re
import sys

FRAGMENT_ORDER = [
    "Type", "EncryptDecrypt", "Allocation", "Accessors", "Capacity",
    "Compare", "Search", "Mutation", "Utility", "Encoding", "WebCodec",
    "Format",
]

KEEP_INLINE = frozenset([
    "__neverc_string_make_view",
    "__neverc_string_empty",
    "__neverc_string_invalid",
    "__neverc_string_cleanup",
    "__neverc_string_wfree_and_null",
    "__neverc_string_decrypt_literal",
    "__neverc_xfree_dec",
    "neverc_string_cstr",
    "neverc_string_data",
    "neverc_string_w_str",
    "neverc_string_wfree",
])

_BLOCK_SIG_RE = re.compile(
    r'^static\s+(?:__inline__\s+)?'
    r'(.+?)'
    r'((?:neverc_string|__neverc_string)_\w+)'
    r'\s*\(([^)]*)\)',
    re.DOTALL,
)


def strip_prelude_wrapper(text: str) -> str:
    """Remove the R\"prelude(...)prelude\" raw-string-literal wrapper."""
    m = re.search(r'R"prelude\((.*?)\)prelude"', text, re.DOTALL)
    return m.group(1) if m else text


def extract_signatures(prelude_dir: str):
    """Yield (return_type, func_name, params) from all .inc fragments.

    Splits each fragment by top-level ``static`` boundaries (column-0)
    so that function bodies of non-matching helper functions (e.g.
    ``__neverc_b64_encode_digit``) are never swallowed into the
    return-type capture of the next ``neverc_string_*`` function.
    """
    seen = set()
    for stem in FRAGMENT_ORDER:
        path = os.path.join(prelude_dir, f"{stem}.inc")
        if not os.path.isfile(path):
            print(f"warning: {path} not found, skipping", file=sys.stderr)
            continue
        with open(path, "r") as f:
            src = strip_prelude_wrapper(f.read())
        blocks = re.split(r'\n(?=static\s)', src)
        for block in blocks:
            block = block.strip()
            if not block.startswith("static"):
                continue
            m = _BLOCK_SIG_RE.search(block)
            if not m:
                continue
            ret_type = " ".join(m.group(1).split())
            name = m.group(2)
            params = " ".join(m.group(3).split())
            if name in KEEP_INLINE or name in seen:
                continue
            seen.add(name)
            yield ret_type, name, params


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("prelude_dir", help="Directory containing .inc fragments")
    parser.add_argument("-o", "--output", required=True, help="Output .inc file")
    args = parser.parse_args()

    sigs = list(extract_signatures(args.prelude_dir))

    decl_lines = []
    decl_lines.append(f"/* {len(sigs)} extern declarations extracted from prelude .inc */")
    decl_lines.append("")

    for ret_type, name, params in sigs:
        decl_lines.append(f"extern {ret_type} {name}({params});")

    decl_lines.append("")
    decl_body = "\n".join(decl_lines)

    wrapper = (
        "//===- BuiltinStringThinHeaderDecls.inc -- auto-generated externs --------===//\n"
        "//\n"
        "// Auto-generated by gen_thin_header.py -- DO NOT EDIT.\n"
        "//\n"
        "// Raw-string-literal body containing extern declarations for all\n"
        "// prelude functions (minus the retained inline helpers listed in\n"
        "// gen_thin_header.py's KEEP_INLINE set).\n"
        "//\n"
        "//===----------------------------------------------------------------------===//\n"
        "\n"
        f'R"thin_decls(\n{decl_body})thin_decls"\n'
    )

    os.makedirs(os.path.dirname(args.output) or ".", exist_ok=True)
    with open(args.output, "w") as f:
        f.write(wrapper)

    print(f"gen_thin_header: wrote {len(sigs)} extern declarations to {args.output}",
          file=sys.stderr)


if __name__ == "__main__":
    main()
