#!/usr/bin/env python3
"""Generate BuiltinStringRuntime.c from prelude .inc fragments.

Strips the R"prelude(...)prelude" raw-string-literal wrapper from each
fragment, concatenates them in the canonical order, and prepends a
storage-class override so all functions get external linkage + forced
emission (via __attribute__((used))) when compiled to bitcode.

Usage:
    python3 gen_string_runtime.py <prelude_dir> -o <output.c>
"""

import argparse
import os
import re
import sys

FRAGMENT_ORDER = [
    "Type", "Allocation", "Accessors", "Capacity", "Compare",
    "Search", "Mutation", "Utility", "Encoding", "WebCodec", "Format",
]


def strip_prelude_wrapper(text: str) -> str:
    m = re.search(r'R"prelude\((.*?)\)prelude"', text, re.DOTALL)
    return m.group(1) if m else text


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("prelude_dir", help="Directory containing .inc fragments")
    parser.add_argument("-o", "--output", required=True, help="Output .c file")
    args = parser.parse_args()

    fragments = []
    for stem in FRAGMENT_ORDER:
        path = os.path.join(args.prelude_dir, f"{stem}.inc")
        if not os.path.isfile(path):
            print(f"warning: {path} not found, skipping", file=sys.stderr)
            continue
        with open(path, "r") as f:
            src = strip_prelude_wrapper(f.read())
        fragments.append((stem, src))

    preamble = """\
/* BuiltinStringRuntime.c -- Auto-generated by gen_string_runtime.py
 *
 * Standalone compilation unit containing all NeverC builtin string
 * prelude function implementations.  Compiled to LLVM bitcode at
 * CMake build time and embedded in the compiler binary.
 *
 * DO NOT EDIT -- regenerate with:
 *   python3 gen_string_runtime.py <prelude_dir> -o BuiltinStringRuntime.c
 */

#define NEVERC_STRING_BUILDING_RUNTIME 1

/* Override `static` and `__inline__` so all functions get plain
 * external linkage.  The original `static __inline__ T foo()`
 * becomes `__attribute__((used)) T foo()` — external linkage,
 * no inline hint (inlining happens after bitcode merge in the
 * user module's optimisation pipeline).  __attribute__((used))
 * prevents DCE from dropping unreferenced definitions. */
#pragma push_macro("static")
#pragma push_macro("__inline__")
#undef static
#undef __inline__
#define static __attribute__((used))
#define __inline__

"""

    epilogue = """\

/* Restore macros for any downstream code. */
#pragma pop_macro("__inline__")
#pragma pop_macro("static")
"""

    os.makedirs(os.path.dirname(args.output) or ".", exist_ok=True)
    with open(args.output, "w") as f:
        f.write(preamble)
        for stem, src in fragments:
            f.write(f"/* === {stem}.inc === */\n")
            f.write(src)
            f.write("\n")
        f.write(epilogue)

    total_lines = sum(src.count("\n") for _, src in fragments)
    print(f"gen_string_runtime: wrote {len(fragments)} fragments "
          f"({total_lines} lines) to {args.output}", file=sys.stderr)


if __name__ == "__main__":
    main()
