#!/usr/bin/env python3
"""Generate MimallocRuntime.c — a wrapper around mimalloc's static.c for
bitcode compilation.

mimalloc already ships a single-file compilation unit (src/static.c) that
includes all other source files.  This script generates a thin wrapper
that sets the required defines and includes static.c.

Usage:
    python3 gen_mimalloc_source.py <mimalloc_src_dir> -o <output.c> [--os linux|darwin|win]
"""

import argparse
import os
import sys

# Configuration for the static override build, shared by every target.
#
# NDEBUG is what selects mimalloc's release configuration.  Without it
# mimalloc defaults to MI_DEBUG=2, which enables assertions, per-block
# padding with canaries, guard pages, free-list encoding and fine-grained
# statistics.  Since the allocator is embedded into every hosted program
# the compiler builds, that default costs roughly 6x in allocation
# throughput and bakes each assertion's __FILE__ -- an absolute path from
# the machine that built the compiler -- into the user's binary.
CORE_DEFINES = {
    "NDEBUG": 1,
    "MI_OVERRIDE": 1,
    "MI_BUILD_SHARED": 0,
    "MI_MALLOC_OVERRIDE": 1,
    "MI_SKIP_COLLECT_ON_EXIT": 1,
}

OS_DEFINES = {
    "linux": {
        "_GNU_SOURCE": 1,
        "_DEFAULT_SOURCE": 1,
        # Mimalloc otherwise falls back to an x86 FS-segment inline-asm
        # memory operand. NeverC materializes that operand as a load from
        # address zero before entering the asm, so every allocation
        # crashes. The LLVM thread-pointer intrinsic is the upstream
        # preferred implementation and works for both Linux variants.
        "MI_USE_BUILTIN_THREAD_POINTER": 1,
    },
    "darwin": {
        "_GNU_SOURCE": 1,
        "_DEFAULT_SOURCE": 1,
    },
    "win": {
        "_WIN32": 1,
        "WIN32": 1,
    },
}


def render_defines(defines):
    return [f"#define {name} {value}" for name, value in defines.items()]


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("mimalloc_src_dir",
                        help="Path to mimalloc source root (contains src/ and include/)")
    parser.add_argument("-o", "--output", required=True, help="Output .c file")
    parser.add_argument("--os", default="linux", choices=sorted(OS_DEFINES),
                        help="Target OS for platform-specific defines")
    args = parser.parse_args()

    src_dir = os.path.join(args.mimalloc_src_dir, "src")
    static_c = os.path.join(src_dir, "static.c")
    if not os.path.isfile(static_c):
        print(f"error: {static_c} not found", file=sys.stderr)
        sys.exit(1)

    include_dir = os.path.join(args.mimalloc_src_dir, "include")
    if not os.path.isdir(include_dir):
        print(f"error: {include_dir} not found", file=sys.stderr)
        sys.exit(1)

    lines = [
        "/* MimallocRuntime.c — Auto-generated by gen_mimalloc_source.py",
        f" * Target OS: {args.os}",
        " *",
        " * DO NOT EDIT — regenerate with:",
        f" *   python3 gen_mimalloc_source.py <mimalloc_src> -o MimallocRuntime.c --os {args.os}",
        " */",
        "",
        *render_defines(CORE_DEFINES),
        "",
        *render_defines(OS_DEFINES[args.os]),
        "",
        # static.c pulls in every other mimalloc translation unit.
        f'#include "{static_c}"',
        "",
    ]

    os.makedirs(os.path.dirname(args.output) or ".", exist_ok=True)
    with open(args.output, "w") as f:
        f.write("\n".join(lines))

    print(f"gen_mimalloc_source: wrote {args.output} (target={args.os})",
          file=sys.stderr)


if __name__ == "__main__":
    main()
