#!/usr/bin/env python3
"""Generate MimallocRuntime.c — a wrapper around mimalloc's static.c for
bitcode compilation.

mimalloc already ships a single-file compilation unit (src/static.c) that
includes all other source files.  This script generates a thin wrapper
that sets the required defines and includes static.c.

Usage:
    python3 gen_mimalloc_source.py <mimalloc_src_dir> -o <output.c> [--os linux|darwin|win]
"""

import argparse
import os
import sys


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("mimalloc_src_dir",
                        help="Path to mimalloc source root (contains src/ and include/)")
    parser.add_argument("-o", "--output", required=True, help="Output .c file")
    parser.add_argument("--os", default="linux", choices=["linux", "darwin", "win"],
                        help="Target OS for platform-specific defines")
    args = parser.parse_args()

    src_dir = os.path.join(args.mimalloc_src_dir, "src")
    static_c = os.path.join(src_dir, "static.c")
    if not os.path.isfile(static_c):
        print(f"error: {static_c} not found", file=sys.stderr)
        sys.exit(1)

    include_dir = os.path.join(args.mimalloc_src_dir, "include")
    if not os.path.isdir(include_dir):
        print(f"error: {include_dir} not found", file=sys.stderr)
        sys.exit(1)

    os_defines = {
        "linux": [
            "#define _GNU_SOURCE 1",
            "#define _DEFAULT_SOURCE 1",
        ],
        "darwin": [
            "#define _GNU_SOURCE 1",
            "#define _DEFAULT_SOURCE 1",
        ],
        "win": [
            "#define _WIN32 1",
            "#define WIN32 1",
        ],
    }

    lines = []
    lines.append("/* MimallocRuntime.c — Auto-generated by gen_mimalloc_source.py")
    lines.append(f" * Target OS: {args.os}")
    lines.append(" *")
    lines.append(" * DO NOT EDIT — regenerate with:")
    lines.append(f" *   python3 gen_mimalloc_source.py <mimalloc_src> -o MimallocRuntime.c --os {args.os}")
    lines.append(" */")
    lines.append("")

    # Core defines for static override build
    lines.append("#define MI_OVERRIDE 1")
    lines.append("#define MI_BUILD_SHARED 0")
    lines.append("#define MI_MALLOC_OVERRIDE 1")
    lines.append("#define MI_SKIP_COLLECT_ON_EXIT 1")
    lines.append("")

    for d in os_defines.get(args.os, []):
        lines.append(d)
    lines.append("")

    # Include static.c which pulls in everything
    lines.append(f'#include "{static_c}"')
    lines.append("")

    os.makedirs(os.path.dirname(args.output) or ".", exist_ok=True)
    with open(args.output, "w") as f:
        f.write("\n".join(lines))

    print(f"gen_mimalloc_source: wrote {args.output} (target={args.os})",
          file=sys.stderr)


if __name__ == "__main__":
    main()
