#include "neverc/Plugin/PluginPhaseSchema.h"
#include "gtest/gtest.h"
#include <array>
#include <cstdint>

namespace {

TEST(PluginPhaseSchemaTest, PublishesSixStableDriverPhases) {
  static_assert(NEVERC_BUILTIN_DRIVER_PHASE_COUNT == 6);
  static_assert(NEVERC_BUILTIN_PHASE_COUNT == 130);
  static_assert(NEVERC_BUILTIN_DYNCODE_PHASE_COUNT == 34);
  static_assert(NEVERC_EXTENSION_FAMILY_COUNT == 8);
  const std::array<uint64_t, 6> IDs = {
      NEVERC_PHASE_DRIVER_RAW_ARGUMENTS_LOW,
      NEVERC_PHASE_DRIVER_PARSED_ARGUMENTS_LOW,
      NEVERC_PHASE_DRIVER_SELECT_TOOLCHAIN_LOW,
      NEVERC_PHASE_DRIVER_BUILD_ACTIONS_LOW,
      NEVERC_PHASE_DRIVER_BUILD_JOBS_LOW,
      NEVERC_PHASE_DRIVER_EXECUTE_JOB_LOW,
  };
  for (size_t I = 0; I != IDs.size(); ++I)
    for (size_t J = I + 1; J != IDs.size(); ++J)
      EXPECT_NE(IDs[I], IDs[J]);

  EXPECT_EQ(NEVERC_PHASE_DRIVER_RAW_ARGUMENTS_POLICY,
            NEVERC_PHASE_OBSERVABLE | NEVERC_PHASE_INTERCEPTABLE);
  EXPECT_EQ(NEVERC_PHASE_DRIVER_PARSED_ARGUMENTS_POLICY,
            NEVERC_PHASE_OBSERVABLE | NEVERC_PHASE_INTERCEPTABLE);
  EXPECT_EQ(NEVERC_PHASE_DRIVER_SELECT_TOOLCHAIN_POLICY,
            NEVERC_PHASE_OBSERVABLE | NEVERC_PHASE_INTERCEPTABLE |
                NEVERC_PHASE_REPLACEABLE);
  EXPECT_EQ(NEVERC_PHASE_DRIVER_BUILD_ACTIONS_POLICY,
            NEVERC_PHASE_DRIVER_SELECT_TOOLCHAIN_POLICY);
  EXPECT_EQ(NEVERC_PHASE_DRIVER_BUILD_JOBS_POLICY,
            NEVERC_PHASE_DRIVER_SELECT_TOOLCHAIN_POLICY);
  EXPECT_EQ(NEVERC_PHASE_DRIVER_EXECUTE_JOB_POLICY,
            NEVERC_PHASE_DRIVER_SELECT_TOOLCHAIN_POLICY);
  EXPECT_EQ((NEVERC_PHASE_DRIVER_EXECUTE_JOB_POLICY &
             NEVERC_PHASE_SKIPPABLE_WITH_PROOF),
            0U);
  EXPECT_STREQ(NEVERC_PHASE_DRIVER_RAW_ARGUMENTS_DOMAIN, "driver");
  EXPECT_STREQ(NEVERC_PHASE_DRIVER_RAW_ARGUMENTS_VERIFIER,
               "neverc.driver.verify_raw_arguments");
  EXPECT_EQ(NEVERC_PHASE_DRIVER_RAW_ARGUMENTS_GATE,
            NEVERC_PHASE_GATE_TRANSITION);
  EXPECT_EQ(NEVERC_PHASE_DRIVER_RAW_ARGUMENTS_STABILITY,
            NEVERC_PHASE_STABILITY_STABLE);
  EXPECT_EQ(NEVERC_PHASE_DRIVER_RAW_ARGUMENTS_BUILTIN_FALLBACK, NEVERC_TRUE);
  EXPECT_STREQ(NEVERC_EXTENSION_FAMILY_0_NAMESPACE, "neverc.driver.extension");
}

} // namespace
