//===- PluginSDKGenerationSingleHeader.cpp - single-header probe TU -------===//
//
// Includes ONLY the distributed single header (generated by
// utils/plugin-api/gen-single-header.py) and exposes its probe table. Kept in a
// separate translation unit from PluginSDKGenerationTests.cpp, which includes
// the modular aggregate, so the two forms can be compared without guard
// collisions in one TU.
//
//===----------------------------------------------------------------------===//

#include NEVERC_PLUGINSDK_SINGLE_HEADER

#include "PluginSDKGenerationProbe.h"

extern "C" const NevercSDKGenProbe *
nevercSDKGenSingleHeaderProbes(std::size_t *Count) {
  static const NevercSDKGenProbe Probes[] = {
#define NEVERC_ABI_VALUE(expr)                                                  \
  {#expr, static_cast<unsigned long long>(expr)},
#define NEVERC_ABI_SIZE(type)                                                   \
  {"sizeof:" #type, static_cast<unsigned long long>(sizeof(type))},
#include "PluginSDKGenerationValues.def"
#undef NEVERC_ABI_VALUE
#undef NEVERC_ABI_SIZE
  };
  *Count = sizeof(Probes) / sizeof(Probes[0]);
  return Probes;
}
