#!/usr/bin/env python3
"""Generate the Python Phase catalog from NeverC's normative JSON schema."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys


REPOSITORY_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_SCHEMA = (
    REPOSITORY_ROOT
    / "neverc/include/neverc/Plugin/Schema/PhaseSchema.json"
)
DEFAULT_OUTPUT = (
    REPOSITORY_ROOT / "pluginsdk/python/neverc_plugin/phases.py"
)


def render(schema: dict[str, object]) -> str:
    phases = schema.get("phases")
    if not isinstance(phases, list):
        raise ValueError("phase schema has no phases list")

    records: list[tuple[str, str, int, int, str]] = []
    seen_symbols: set[str] = set()
    seen_ids: set[tuple[int, int]] = set()
    for phase in phases:
        if not isinstance(phase, dict):
            raise ValueError("phase entry is not an object")
        symbol = phase.get("symbol")
        name = phase.get("name")
        domain = phase.get("domain")
        identifier = phase.get("id")
        if (
            not isinstance(symbol, str)
            or not symbol.isidentifier()
            or not isinstance(name, str)
            or not isinstance(domain, str)
            or not isinstance(identifier, list)
            or len(identifier) != 2
            or not all(isinstance(value, str) for value in identifier)
        ):
            raise ValueError(f"invalid phase schema entry: {phase!r}")
        high, low = (int(value, 0) for value in identifier)
        if symbol in seen_symbols or (high, low) in seen_ids:
            raise ValueError(f"duplicate phase symbol or ID: {symbol}")
        seen_symbols.add(symbol)
        seen_ids.add((high, low))
        records.append((symbol, name, high, low, domain))

    lines = [
        '"""Generated NeverC phase constants; do not edit by hand.',
        "",
        "Generated by utils/plugin-api/gen-python-phases.py from",
        "neverc/include/neverc/Plugin/Schema/PhaseSchema.json.",
        '"""',
        "",
        "from .api import Phase",
        "",
    ]
    for symbol, name, high, low, _domain in records:
        lines.append(
            f'{symbol} = Phase(0x{high:016x}, 0x{low:016x}, {name!r})'
        )
    lines.extend(["", "ALL_PHASES = ("])
    lines.extend(f"    {symbol}," for symbol, *_rest in records)
    lines.extend([")", "", "BY_ID = {"])
    lines.extend(
        f"    (phase.high, phase.low): phase for phase in ALL_PHASES"
        for _ in range(1)
    )
    lines.extend(["}", "", "BY_NAME = {"])
    lines.append("    phase.name: phase for phase in ALL_PHASES")
    lines.extend(["}", "", "DOMAIN_PHASES = {"])
    domains = sorted({domain for *_head, domain in records})
    for domain in domains:
        symbols = [symbol for symbol, *_middle, item_domain in records if item_domain == domain]
        lines.append(f"    {domain!r}: (")
        lines.extend(f"        {symbol}," for symbol in symbols)
        lines.append("    ),")
    lines.extend(["}", "", "__all__ = ["])
    lines.extend(f"    {symbol!r}," for symbol, *_rest in records)
    lines.extend(
        [
            '    "ALL_PHASES",',
            '    "BY_ID",',
            '    "BY_NAME",',
            '    "DOMAIN_PHASES",',
            "]",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--schema", type=Path, default=DEFAULT_SCHEMA)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()

    with arguments.schema.open("r", encoding="utf-8") as stream:
        content = render(json.load(stream))

    if arguments.check:
        try:
            existing = arguments.output.read_text(encoding="utf-8")
        except FileNotFoundError:
            existing = ""
        if existing != content:
            print(f"out of date: {arguments.output}", file=sys.stderr)
            return 1
        return 0

    arguments.output.parent.mkdir(parents=True, exist_ok=True)
    arguments.output.write_text(content, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
