#!/usr/bin/env python3
"""Generate the runtime GKI compatibility table from checked manifests."""

import argparse
import json
from pathlib import Path
import sys


TOOLS_ROOT = Path(__file__).resolve().parent
RUNTIME_ROOT = TOOLS_ROOT.parent
DEFAULT_MANIFEST_ROOT = RUNTIME_ROOT / "arm64/gki-manifests"
DEFAULT_OUTPUT = RUNTIME_ROOT / "src/nvk_compat_table.inc"

PROFILE_METADATA = {
    510: (5, 10, 12, 0xFFFFFFC008000000),
    515: (5, 15, 13, 0xFFFFFFC008000000),
    601: (6, 1, 14, 0xFFFFFFC008000000),
    606: (6, 6, 15, 0xFFFFFFC080000000),
    612: (6, 12, 16, 0xFFFFFFC080000000),
    618: (6, 18, 17, 0xFFFFFFC080000000),
}

LAYOUT_FIELDS = (
    ("task_tasks", "task_struct", "tasks"),
    ("task_mm", "task_struct", "mm"),
    ("task_pid", "task_struct", "pid"),
    ("task_group_leader", "task_struct", "group_leader"),
    ("task_real_cred", "task_struct", "real_cred"),
    ("task_cred", "task_struct", "cred"),
    ("task_comm", "task_struct", "comm"),
    ("cred_uid", "cred", "uid"),
    ("cred_securebits", "cred", "securebits"),
    ("cred_cap_inheritable", "cred", "cap_inheritable"),
    ("vma_start", "vm_area_struct", "vm_start"),
    ("vma_end", "vm_area_struct", "vm_end"),
    ("vma_mm", "vm_area_struct", "vm_mm"),
    ("vma_page_prot", "vm_area_struct", "vm_page_prot"),
    ("vma_flags", "vm_area_struct", "vm_flags"),
    ("vma_pgoff", "vm_area_struct", "vm_pgoff"),
    ("vma_file", "vm_area_struct", "vm_file"),
    ("vmap_va_start", "vmap_area", "va_start"),
    ("vmap_va_end", "vmap_area", "va_end"),
)


def member(layouts, structure, field):
    try:
        return layouts[structure]["members"][field]
    except KeyError as error:
        raise ValueError(
            f"manifest lacks {structure}.{field}"
        ) from error


def load_profiles(root):
    profiles = []
    for profile, metadata in PROFILE_METADATA.items():
        path = root / f"{profile}.json"
        manifest = json.loads(path.read_text(encoding="utf-8"))
        if manifest.get("profile") != profile:
            raise ValueError(f"{path}: profile mismatch")
        profiles.append((profile, metadata, manifest))
    return profiles


def render_table(profiles):
    lines = [
        "/* SPDX-License-Identifier: GPL-2.0 */",
        "/*",
        " * Generated by tools/generate-compat-table.py from the checked",
        " * arm64/gki-manifests/*.json files.  Do not edit by hand.",
        " */",
        "",
        "struct neverc_krt_version_entry {",
        "\tint kv;",
        "\tu32 major;",
        "\tu32 minor;",
        "\tu32 android_version;",
        "\tunsigned long module_size;",
        "\tunsigned long file_dentry_off;",
        "\tunsigned long off_init;",
        "\tunsigned long off_exit;",
        "\tunsigned long kimage_vaddr;",
        "\tstruct neverc_krt_gki_layout layout;",
        "};",
        "",
        f"#define NEVERC_KRT_VERSION_TABLE_LEN {len(profiles)}",
        "",
        "static const struct neverc_krt_version_entry",
        "_neverc_krt_version_table[NEVERC_KRT_VERSION_TABLE_LEN] = {",
    ]

    for profile, metadata, manifest in profiles:
        major, minor, android_version, kimage_vaddr = metadata
        layouts = manifest["layouts"]
        file_dentry = (
            member(layouts, "file", "f_path")
            + member(layouts, "path", "dentry")
        )
        lines.extend(
            [
                "\t{",
                f"\t\t.kv = {profile},",
                f"\t\t.major = {major},",
                f"\t\t.minor = {minor},",
                f"\t\t.android_version = {android_version},",
                f"\t\t.module_size = {layouts['module']['size']},",
                f"\t\t.file_dentry_off = {file_dentry},",
                f"\t\t.off_init = {member(layouts, 'module', 'init')},",
                f"\t\t.off_exit = {member(layouts, 'module', 'exit')},",
                f"\t\t.kimage_vaddr = 0x{kimage_vaddr:016X}UL,",
                "\t\t.layout = {",
            ]
        )
        for output_name, structure, field in LAYOUT_FIELDS:
            lines.append(
                f"\t\t\t.{output_name} = "
                f"{member(layouts, structure, field)},"
            )
        lines.extend(["\t\t},", "\t},"])

    lines.extend(["};", ""])
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(
        description="generate runtime GKI compatibility table"
    )
    parser.add_argument(
        "--manifest-root",
        type=Path,
        default=DEFAULT_MANIFEST_ROOT,
    )
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if the checked-in table is stale",
    )
    args = parser.parse_args()

    try:
        rendered = render_table(load_profiles(args.manifest_root))
        if args.check:
            current = args.output.read_text(encoding="utf-8")
            if current != rendered:
                raise ValueError(
                    f"{args.output} is stale; rerun generate-compat-table.py"
                )
        else:
            args.output.write_text(rendered, encoding="utf-8")
    except (json.JSONDecodeError, OSError, ValueError) as error:
        print(f"generate-compat-table: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
