/*
 * SHA-512/224 — FIPS 180-4, Section 6.7.
 * Same compression as SHA-512, different IV, output truncated to 28 bytes.
 * IV generated by SHA-512("SHA-512/224") as specified in FIPS 180-4 Section 5.3.6.
 */
#include "neverc/std/crypto/sha512_224.h"
#include "neverc/std/_platform.h"
#include <string.h>

void neverc_sha512_224_init(neverc_sha512_224_ctx *ctx) {
    if (!ctx) return;
    memset(ctx, 0, sizeof(*ctx));
    ctx->state[0] = 0x8C3D37C819544DA2ULL;
    ctx->state[1] = 0x73E1996689DCD4D6ULL;
    ctx->state[2] = 0x1DFAB7AE32FF9C82ULL;
    ctx->state[3] = 0x679DD514582F9FCFULL;
    ctx->state[4] = 0x0F6D2B697BD44DA8ULL;
    ctx->state[5] = 0x77E36F7304C48942ULL;
    ctx->state[6] = 0x3F9D85A86A1D36C8ULL;
    ctx->state[7] = 0x1112E6AD91D692A1ULL;
}

void neverc_sha512_224_update(neverc_sha512_224_ctx *ctx, const uint8_t *data, size_t len) {
    neverc_sha512_update(ctx, data, len);
}

void neverc_sha512_224_final(neverc_sha512_224_ctx *ctx, uint8_t digest[28]) {
    if (!digest) return;
    uint8_t full[64];
    neverc_sha512_final(ctx, full);
    memcpy(digest, full, 28);
    neverc_platform_secure_zero(full, sizeof(full));
}

void neverc_sha512_224_sum(const uint8_t *data, size_t len, uint8_t digest[28]) {
    if (!digest) return;
    if (len > 0 && !data) {
        memset(digest, 0, 28);
        return;
    }
    neverc_sha512_224_ctx ctx;
    neverc_sha512_224_init(&ctx);
    neverc_sha512_224_update(&ctx, data, len);
    neverc_sha512_224_final(&ctx, digest);
}
