#!/usr/bin/env python3
"""Reproduce P0 semantics extraction and scalar sequencing differential checks."""

import argparse
import json
import subprocess
import sys
import tempfile
from pathlib import Path


def run(command, **kwargs):
    result = subprocess.run([str(x) for x in command], text=True,
                            capture_output=True, **kwargs)
    if result.returncode:
        sys.stderr.write(result.stderr)
        result.check_returncode()
    return result.stdout


def walk(value):
    if isinstance(value, dict):
        yield value
        for child in value.values():
            yield from walk(child)
    elif isinstance(value, list):
        for child in value:
            yield from walk(child)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--helper", required=True, type=Path)
    parser.add_argument("--neverc", required=True, type=Path)
    parser.add_argument("--llvm", required=True, type=Path)
    parser.add_argument("--output-dir", required=True, type=Path)
    args = parser.parse_args()
    args.output_dir.mkdir(parents=True, exist_ok=False)
    base = Path(__file__).resolve().parent
    clang = args.llvm / "bin/clang"
    clang_cpp = args.llvm / "bin/clang++"
    resource = run([clang, "-print-resource-dir"]).strip()

    def extract(source):
        return json.loads(run([args.helper, source, "--", "-std=c++17",
                              "-resource-dir", resource]))

    identities = extract(base / "fixtures/identities.cpp")
    (args.output_dir / "identities.json").write_text(json.dumps(identities, indent=2) + "\n")
    assert len(identities["namespaces"]) == 1
    record, = identities["records"]
    assert record["aggregate"] and len(record["fields"]) == 2
    assert record["fields"][0]["type"]["canonical"] == "int"
    assert record["fields"][1]["type"]["canonical"] == "unsigned int"
    overloads = [f for f in identities["functions"] if f["name"] == "score"]
    assert len(overloads) == 2 and overloads[0]["id"] != overloads[1]["id"]
    calls = [n for n in walk(identities) if n.get("kind") == "CallExpr"]
    assert {c["callee"] for c in calls} == {f["id"] for f in overloads}
    assert all(c["location"]["line"] == 6 for c in calls)

    source = base / "fixtures/sequencing.cpp"
    semantics = extract(source)
    json_path = args.output_dir / "sequencing.json"
    json_path.write_text(json.dumps(semantics, indent=2) + "\n")
    nc_path = args.output_dir / "sequencing.nc"
    run([sys.executable, base / "emit-sequencing.py", json_path, nc_path])
    # Semantic identity and generated bytes must be independent of fixture root.
    with tempfile.TemporaryDirectory(prefix="neverc-p0-relocated-") as temp:
        relocated = Path(temp) / source.name
        relocated.write_bytes(source.read_bytes())
        assert extract(relocated) == semantics

    invalid = args.output_dir / "invalid.cpp"
    invalid.write_text("int broken( {\n")
    failure = subprocess.run([str(args.helper), str(invalid), "--", "-std=c++17"],
                             text=True, capture_output=True)
    assert failure.returncode and not failure.stdout

    observations = []
    for optimization in ("-O0", "-O2"):
        level = optimization[1:]
        harness = args.output_dir / f"harness-{level}.o"
        reference = args.output_dir / f"reference-{level}.o"
        generated = args.output_dir / f"generated-{level}.o"
        run([clang, optimization, "-c", base / "fixtures/harness.c", "-o", harness])
        run([clang_cpp, "-std=c++17", optimization, "-c", source, "-o", reference])
        run([args.neverc, optimization, "-c", nc_path, "-o", generated])
        results = {}
        for label, module in (("reference", reference), ("generated", generated)):
            executable = args.output_dir / f"{label}-{level}"
            linker = clang if label == "reference" else args.neverc
            run([linker, harness, module, "-o", executable])
            values = [int(v) for v in run([executable]).split()]
            assert len(values) == 2 and values[0] in (2235286, 2325286), values
            assert values[1] == 1603, values
            if label == "generated":
                assert values[0] == 2235286, values
            results[label] = values
        observations.append({"optimization": optimization, **results})
    result = {"status": "passed", "observations": observations,
              "checks": ["resolved-overloads", "aggregate-types-and-layout",
                         "source-locations", "root-relocation", "invalid-source-no-json",
                         "assignment-order", "argument-order-permitted-set",
                         "short-circuit-effects", "shift-order", "full-scalar-results"]}
    (args.output_dir / "verification.json").write_text(json.dumps(result, indent=2) + "\n")
    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
