#include "neverc/Foundation/Std/BuiltinStd.h"
#include "neverc/Foundation/Builtin/BuiltinStringNames.h"
#include "neverc/Foundation/Std/StdModule.h"

using namespace neverc;

bool BuiltinStd::isStdRuntimeFunction(llvm::StringRef Name) {
  return Name.starts_with(StdModule::FuncPrefix) &&
         !Name.starts_with(BuiltinStringNames::PublicFunctionPrefix);
}

#include "BuiltinStdBitcode.h" // generated by bootstrap

unsigned BuiltinStd::getEmbeddedModuleCount() {
  return kStdBitcodeEntryCount;
}

std::pair<llvm::StringRef, llvm::StringRef>
BuiltinStd::getEmbeddedModule(unsigned Idx) {
  if (Idx >= kStdBitcodeEntryCount)
    return {};
  const auto &E = kStdBitcodeEntries[Idx];
  if (E.len == 0)
    return {};
  return {llvm::StringRef(E.name),
          llvm::StringRef(reinterpret_cast<const char *>(E.data), E.len)};
}
