#!/usr/bin/env python3
"""Compile all NeverC std library .c files to individual LLVM bitcode and
generate an embedded C header with a lookup table.

Usage:
    python3 build_std_bitcode.py <neverc> <std_src_dir> <std_include_dir> -o <output.h>

Each .c is compiled to .bc in a temporary directory.  The script then
emits a single C header containing:

  1. One ``static const unsigned char kStdBC_<name>[]`` per module.
  2. A ``StdBitcodeEntry`` table for runtime iteration.

No external linker (llvm-link) is needed — the compiler's
StdRuntimeLinkerPass merges the modules at compile time using
llvm::Linker::linkModules.
"""

import argparse
import glob
import os
import subprocess
import sys
import tempfile


def sanitize_name(rel_path: str) -> str:
    """Convert a relative path like 'crypto/sha256/sha256.c' to 'crypto_sha256_sha256'."""
    return rel_path.replace(os.sep, "_").replace("/", "_").replace(".c", "")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("neverc", help="Path to neverc compiler binary")
    parser.add_argument("std_src_dir", help="Path to std/src directory")
    parser.add_argument("std_include_dir", help="Path to std/include directory")
    parser.add_argument("--prefix-map", action="append", default=[],
                        metavar="FROM=TO",
                        help="Base path remapping applied ahead of this "
                             "runtime's own source mappings (repeatable)")
    parser.add_argument("-o", "--output", required=True,
                        help="Output .h header file")
    args = parser.parse_args()

    sources = sorted(glob.glob(
        os.path.join(args.std_src_dir, "**", "*.c"), recursive=True))
    sources = [s for s in sources if not s.endswith(".h")]

    if not sources:
        print(f"error: no .c files found in {args.std_src_dir}",
              file=sys.stderr)
        sys.exit(1)

    os.makedirs(os.path.dirname(args.output) or ".", exist_ok=True)

    entries = []  # (sanitized_name, bc_bytes)

    src_dir_abs = os.path.abspath(args.std_src_dir)
    inc_dir_abs = os.path.abspath(args.std_include_dir)

    # Clang resolves prefix maps last-match-wins, so the caller's general
    # roots go first and the install-tree names below override them.  Those
    # names are what lets a debugger find std sources under the install
    # prefix, so they must survive.
    path_mapping = [f"-ffile-prefix-map={m}" for m in args.prefix_map] + [
        f"-fdebug-prefix-map={src_dir_abs}=runtime/std/src",
        f"-fdebug-prefix-map={inc_dir_abs}=runtime/std/include",
    ]

    with tempfile.TemporaryDirectory(prefix="neverc_std_bc_") as tmpdir:
        for src in sources:
            rel = os.path.relpath(src, args.std_src_dir)
            name = sanitize_name(rel)
            bc_path = os.path.join(tmpdir, name + ".bc")

            cmd = [
                args.neverc,
                "-c", "-emit-llvm", "-O2",
                "-gline-tables-only",
                "-fno-builtin-std",
                "-fno-lto",
                "-ffreestanding", "-std=gnu11", "-w",
                f"-I{inc_dir_abs}",
                *path_mapping,
                os.path.abspath(src), "-o", bc_path,
            ]
            print(f"  [bc] {rel}", file=sys.stderr)
            subprocess.check_call(cmd)

            with open(bc_path, "rb") as f:
                bc_data = f.read()
            entries.append((name, bc_data))

    # Emit the header
    lines = []
    lines.append("/* Auto-generated by build_std_bitcode.py — DO NOT EDIT. */")
    lines.append("")

    total_bytes = 0
    for name, data in entries:
        var = f"kStdBC_{name}"
        lines.append(f"static const unsigned char {var}[] = {{")
        for i in range(0, len(data), 16):
            chunk = data[i:i + 16]
            hex_vals = ", ".join(f"0x{b:02x}" for b in chunk)
            lines.append(f"  {hex_vals},")
        lines.append("};")
        lines.append("")
        total_bytes += len(data)

    lines.append("struct StdBitcodeEntry {")
    lines.append("  const char *name;")
    lines.append("  const unsigned char *data;")
    lines.append("  unsigned int len;")
    lines.append("};")
    lines.append("")
    lines.append(f"static const StdBitcodeEntry kStdBitcodeEntries[] = {{")
    for name, data in entries:
        var = f"kStdBC_{name}"
        lines.append(f'  {{"{name}", {var}, sizeof({var})}},')
    lines.append("};")
    lines.append("")
    lines.append(f"static const unsigned int kStdBitcodeEntryCount = "
                 f"{len(entries)};")
    lines.append("")

    with open(args.output, "w") as f:
        f.write("\n".join(lines))

    print(f"build_std_bitcode: {len(entries)} modules, "
          f"{total_bytes} bytes total -> {args.output}", file=sys.stderr)


if __name__ == "__main__":
    main()
