
const llvm::Triple &T = Target.getTriple();
switch (Syntax) {
case AttributeCommonInfo::Syntax::AS_GNU:
  return llvm::StringSwitch<int>(Name)
      .Case("aarch64_sve_pcs", 1)
      .Case("aarch64_vector_pcs", 1)
      .Case("acquire_handle", 1)
      .Case("address_space", 1)
      .Case("alias", 1)
      .Case("align_value", 1)
      .Case("aligned", 1)
      .Case("alloc_align", 1)
      .Case("alloc_size", 1)
      .Case("always_destroy", 1)
      .Case("always_inline", 1)
      .Case("analyzer_noreturn", 1)
      .Case("annotate", 1)
      .Case("interrupt", true && (T.getArch() == llvm::Triple::x86_64) ? 1 : 0)
      .Case("no_caller_saved_registers",
            true && (T.getArch() == llvm::Triple::x86_64) ? 1 : 0)
      .Case("nocf_check", true && (T.getArch() == llvm::Triple::x86_64) ? 1 : 0)
      .Case("argument_with_type_tag", 1)
      .Case("pointer_with_type_tag", 1)
      .Case("__neverc_arm_builtin_alias",
            true && (T.getArch() == llvm::Triple::aarch64) ? 1 : 0)
      .Case("arm_sve_vector_bits", 1)
      .Case("artificial", 1)
      .Case("assume_aligned", 1)
      .Case("assume", 1)
      .Case("availability", 1)
      .Case("available_only_in_default_eval_method", 1)
      .Case("btf_decl_tag", 1)
      .Case("btf_type_tag", 1)
      .Case("neverc_builtin_alias", 1)
      .Case("cdecl", 1)
      .Case("guard", true && (T.getOS() == llvm::Triple::Win32) ? 1 : 0)
      .Case("cpu_dispatch", 1)
      .Case("cpu_specific", 1)
      .Case("callback", 1)
      .Case("carries_dependency", 1)
      .Case("cleanup", 1)
      .Case("code_align", 1)
      .Case("cold", 1)
      .Case("common", 1)
      .Case("const", 1)
      .Case("__const", 1)
      .Case("constructor", 1)
      .Case("convergent", 1)
      .Case("dllexport",
            true && (Target.getTriple().hasDLLImportExport()) ? 1 : 0)
      .Case("dllimport",
            true && (Target.getTriple().hasDLLImportExport()) ? 1 : 0)
      .Case("deprecated", 1)
      .Case("destructor", 1)
      .Case("diagnose_as_builtin", 1)
      .Case("diagnose_if", 1)
      .Case("disable_tail_calls", 1)
      .Case("disable_try_stmt", 1)
      .Case("enable_if", 1)
      .Case("enforce_tcb", 1)
      .Case("enforce_tcb_leaf", 1)
      .Case("enum_extensibility", 1)
      .Case("error", 1)
      .Case("warning", 1)
      .Case("ext_vector_type", 1)
      .Case("fallthrough", 1)
      .Case("fastcall", 1)
      .Case("flag_enum", 1)
      .Case("flatten", 1)
      .Case("format", 1)
      .Case("format_arg", 1)
      .Case("function_return",
            true && (T.getArch() == llvm::Triple::x86_64) ? 1 : 0)
      .Case("gnu_inline", 1)
      .Case("hot", 1)
      .Case("ifunc", true && (T.getObjectFormat() == llvm::Triple::ELF ||
                              T.getObjectFormat() == llvm::Triple::MachO)
                         ? 1
                         : 0)
      .Case("internal_linkage", 1)
      .Case("lto_visibility_public", 1)
      .Case("leaf", 1)
      .Case("loader_uninitialized", 1)
      .Case("ms_abi", 1)
      .Case("ms_struct", 1)
      .Case("matrix_type", 1)
      .Case("may_alias", 1)
      .Case("maybe_undef", 1)
      .Case("minsize", 1)
      .Case("min_vector_width", 1)
      .Case("mode", 1)
      .Case("musttail", 1)
      .Case("naked", 1)
      .Case("neon_polyvector_type", 1)
      .Case("neon_vector_type", 1)
      .Case("no_builtin", 1)
      .Case("nocommon", 1)
      .Case("nodebug", 1)
      .Case("noderef", 1)
      .Case("no_destroy", 1)
      .Case("noduplicate", 1)
      .Case("noescape", 1)
      .Case("noinline", 1)
      .Case("nomerge", 1)
      .Case("no_randomize_layout", 1)
      .Case("noreturn", 1)
      .Case("no_speculative_load_hardening", 1)
      .Case("no_split_stack", 1)
      .Case("no_stack_protector", 1)
      .Case("nothrow", 1)
      .Case("nouwtable", 1)
      .Case("nonnull", 1)
      .Case("not_tail_called", 1)
      .Case("optnone", 1)
      .Case("overloadable", 1)
      .Case("override", 1)
      .Case("packed", 1)
      .Case("pass_object_size", 1)
      .Case("pass_dynamic_object_size", 1)
      .Case("patchable_function_entry",
            true && (T.getArch() == llvm::Triple::aarch64 ||
                     T.getArch() == llvm::Triple::x86 ||
                     T.getArch() == llvm::Triple::x86_64)
                ? 1
                : 0)
      .Case("preferred_type", 1)
      .Case("preserve_all", 1)
      .Case("preserve_most", 1)
      .Case("pure", 1)
      .Case("randomize_layout", 1)
      .Case("enforce_read_only_placement", 1)
      .Case("regcall", 1)
      .Case("regparm", 1)
      .Case("release_handle", 1)
      .Case("malloc", 1)
      .Case("retain", 1)
      .Case("returns_nonnull", 1)
      .Case("returns_twice", 1)
      .Case("section", 1)
      .Case("selectany", 1)
      .Case("sentinel", 1)
      .Case("speculative_load_hardening", 1)
      .Case("stdcall", 1)
      .Case("suppress", 1)
      .Case("sysv_abi", 1)
      .Case("tls_model", 1)
      .Case("target", 1)
      .Case("target_clones", 1)
      .Case("target_version", 1)
      .Case("transparent_union", 1)
      .Case("type_tag_for_datatype", 1)
      .Case("type_visibility", 1)
      .Case("unavailable", 1)
      .Case("uninitialized", 1)
      .Case("unsafe_buffer_usage", 1)
      .Case("unused", 1)
      .Case("use_handle", 1)
      .Case("used", 1)
      .Case("vectorcall", 1)
      .Case("vector_size", 1)
      .Case("visibility", 1)
      .Case("volatile", 1)
      .Case("warn_unused", 1)
      .Case("warn_unused_result", 1)
      .Case("weak", 1)
      .Case("weak_import", 1)
      .Case("weakref", 1)
      .Case("force_align_arg_pointer",
            true && (T.getArch() == llvm::Triple::x86_64) ? 1 : 0)
      .Case("zero_call_used_regs", 1)
      .Default(0);
case AttributeCommonInfo::Syntax::AS_Declspec:
  return llvm::StringSwitch<int>(Name)
      .Case("align", 1)
      .Case("guard", true && (T.getOS() == llvm::Triple::Win32) ? 1 : 0)
      .Case("cpu_dispatch", 1)
      .Case("cpu_specific", 1)
      .Case("code_seg", 1)
      .Case("dllexport",
            true && (Target.getTriple().hasDLLImportExport()) ? 1 : 0)
      .Case("dllimport",
            true && (Target.getTriple().hasDLLImportExport()) ? 1 : 0)
      .Case("deprecated", 1)
      .Case("disable_try_stmt", 1)
      .Case("allocator", 1)
      .Case("naked", 1)
      .Case("noalias", 1)
      .Case("noinline", 1)
      .Case("noreturn", 1)
      .Case("safebuffers", 1)
      .Case("nothrow", 1)
      .Case("override", 1)
      .Case("restrict", 1)
      .Case("allocate", 1)
      .Case("selectany", 1)
      .Case("strict_gs_check", 1)
      .Case("thread", 1)
      .Case("volatile", 1)
      .Case("property", 1)
      .Default(0);
case AttributeCommonInfo::Syntax::AS_Microsoft:
  return llvm::StringSwitch<int>(Name).Default(0);
case AttributeCommonInfo::Syntax::AS_Pragma:
  return llvm::StringSwitch<int>(Name).Case("init_seg", 1).Default(0);
case AttributeCommonInfo::Syntax::AS_Bracket: {
  if (ScopeName == "") {
    return llvm::StringSwitch<int>(Name)
        .Case("carries_dependency", 200809)
        .Case("deprecated", 201309)
        .Case("fallthrough", 201603)
        .Case("likely", 201803)
        .Case("noreturn", 200809)
        .Case("unlikely", 201803)
        .Case("maybe_unused", 201603)
        .Case("nodiscard", 201907)
        .Default(0);
  } else if (ScopeName == "clang") {
    return llvm::StringSwitch<int>(Name)
        .Case("aarch64_sve_pcs", 1)
        .Case("aarch64_vector_pcs", 1)
        .Case("acquire_handle", 1)
        .Case("address_space", 1)
        .Case("always_destroy", 1)
        .Case("annotate", 1)
        .Case("argument_with_type_tag", 1)
        .Case("pointer_with_type_tag", 1)
        .Case("__neverc_arm_builtin_alias",
              true && (T.getArch() == llvm::Triple::aarch64) ? 1 : 0)
        .Case("assume", 1)
        .Case("availability", 1)
        .Case("available_only_in_default_eval_method", 1)
        .Case("btf_decl_tag", 1)
        .Case("btf_type_tag", 1)
        .Case("guard", true && (T.getOS() == llvm::Triple::Win32) ? 1 : 0)
        .Case("cpu_dispatch", 1)
        .Case("cpu_specific", 1)
        .Case("callback", 1)
        .Case("code_align", 1)
        .Case("convergent", 1)
        .Case("diagnose_as_builtin", 1)
        .Case("disable_tail_calls", 1)
        .Case("enforce_tcb", 1)
        .Case("enforce_tcb_leaf", 1)
        .Case("enum_extensibility", 1)
        .Case("flag_enum", 1)
        .Case("internal_linkage", 1)
        .Case("lto_visibility_public", 1)
        .Case("loader_uninitialized", 1)
        .Case("matrix_type", 1)
        .Case("maybe_undef", 1)
        .Case("minsize", 1)
        .Case("min_vector_width", 1)
        .Case("musttail", 1)
        .Case("neon_polyvector_type", 1)
        .Case("neon_vector_type", 1)
        .Case("no_builtin", 1)
        .Case("noderef", 1)
        .Case("no_destroy", 1)
        .Case("noduplicate", 1)
        .Case("noescape", 1)
        .Case("nomerge", 1)
        .Case("no_speculative_load_hardening", 1)
        .Case("no_stack_protector", 1)
        .Case("nouwtable", 1)
        .Case("not_tail_called", 1)
        .Case("optnone", 1)
        .Case("overloadable", 1)
        .Case("pass_object_size", 1)
        .Case("pass_dynamic_object_size", 1)
        .Case("preferred_type", 1)
        .Case("preserve_all", 1)
        .Case("preserve_most", 1)
        .Case("enforce_read_only_placement", 1)
        .Case("release_handle", 1)
        .Case("speculative_load_hardening", 1)
        .Case("suppress", 1)
        .Case("type_tag_for_datatype", 1)
        .Case("type_visibility", 1)
        .Case("unavailable", 1)
        .Case("uninitialized", 1)
        .Case("unsafe_buffer_usage", 1)
        .Case("use_handle", 1)
        .Case("vectorcall", 1)
        .Case("weak_import", 1)
        .Default(0);
  } else if (ScopeName == "gnu") {
    return llvm::StringSwitch<int>(Name)
        .Case("alias", 1)
        .Case("aligned", 1)
        .Case("alloc_align", 1)
        .Case("alloc_size", 1)
        .Case("always_inline", 1)
        .Case("interrupt",
              true && (T.getArch() == llvm::Triple::x86_64) ? 1 : 0)
        .Case("no_caller_saved_registers",
              true && (T.getArch() == llvm::Triple::x86_64) ? 1 : 0)
        .Case("nocf_check",
              true && (T.getArch() == llvm::Triple::x86_64) ? 1 : 0)
        .Case("artificial", 1)
        .Case("assume_aligned", 1)
        .Case("cdecl", 1)
        .Case("cleanup", 1)
        .Case("cold", 1)
        .Case("common", 1)
        .Case("const", 1)
        .Case("__const", 1)
        .Case("constructor", 1)
        .Case("dllexport",
              true && (Target.getTriple().hasDLLImportExport()) ? 1 : 0)
        .Case("dllimport",
              true && (Target.getTriple().hasDLLImportExport()) ? 1 : 0)
        .Case("deprecated", 1)
        .Case("destructor", 1)
        .Case("disable_try_stmt", 1)
        .Case("error", 1)
        .Case("warning", 1)
        .Case("fallthrough", 1)
        .Case("fastcall", 1)
        .Case("flatten", 1)
        .Case("format", 1)
        .Case("format_arg", 1)
        .Case("function_return",
              true && (T.getArch() == llvm::Triple::x86_64) ? 1 : 0)
        .Case("gnu_inline", 1)
        .Case("hot", 1)
        .Case("ifunc", true && (T.getObjectFormat() == llvm::Triple::ELF ||
                                T.getObjectFormat() == llvm::Triple::MachO)
                           ? 1
                           : 0)
        .Case("leaf", 1)
        .Case("ms_abi", 1)
        .Case("ms_struct", 1)
        .Case("may_alias", 1)
        .Case("mode", 1)
        .Case("naked", 1)
        .Case("nocommon", 1)
        .Case("nodebug", 1)
        .Case("noinline", 1)
        .Case("no_randomize_layout", 1)
        .Case("noreturn", 1)
        .Case("no_split_stack", 1)
        .Case("no_stack_protector", 1)
        .Case("nothrow", 1)
        .Case("nonnull", 1)
        .Case("override", 1)
        .Case("packed", 1)
        .Case("patchable_function_entry",
              true && (T.getArch() == llvm::Triple::aarch64 ||
                       T.getArch() == llvm::Triple::x86 ||
                       T.getArch() == llvm::Triple::x86_64)
                  ? 1
                  : 0)
        .Case("pure", 1)
        .Case("randomize_layout", 1)
        .Case("regcall", 1)
        .Case("regparm", 1)
        .Case("malloc", 1)
        .Case("retain", 1)
        .Case("returns_nonnull", 1)
        .Case("returns_twice", 1)
        .Case("section", 1)
        .Case("selectany", 1)
        .Case("sentinel", 1)
        .Case("stdcall", 1)
        .Case("sysv_abi", 1)
        .Case("tls_model", 1)
        .Case("target", 1)
        .Case("target_clones", 1)
        .Case("target_version", 1)
        .Case("transparent_union", 1)
        .Case("unused", 1)
        .Case("used", 1)
        .Case("vector_size", 1)
        .Case("visibility", 1)
        .Case("volatile", 1)
        .Case("warn_unused", 1)
        .Case("warn_unused_result", 1)
        .Case("weak", 1)
        .Case("weakref", 1)
        .Case("force_align_arg_pointer",
              true && (T.getArch() == llvm::Triple::x86_64) ? 1 : 0)
        .Case("zero_call_used_regs", 1)
        .Default(0);
  } else if (ScopeName == "gsl") {
    return llvm::StringSwitch<int>(Name).Case("suppress", 1).Default(0);
  } else if (ScopeName == "neverc") {
    return llvm::StringSwitch<int>(Name)
        .Case("aarch64_sve_pcs", 1)
        .Case("aarch64_vector_pcs", 1)
        .Case("acquire_handle", 1)
        .Case("address_space", 1)
        .Case("always_destroy", 1)
        .Case("always_inline", 1)
        .Case("annotate", 1)
        .Case("annotate_type", 1)
        .Case("argument_with_type_tag", 1)
        .Case("pointer_with_type_tag", 1)
        .Case("__neverc_arm_builtin_alias",
              true && (T.getArch() == llvm::Triple::aarch64) ? 1 : 0)
        .Case("assume", 1)
        .Case("availability", 1)
        .Case("available_only_in_default_eval_method", 1)
        .Case("btf_decl_tag", 1)
        .Case("btf_type_tag", 1)
        .Case("builtin_alias", 1)
        .Case("guard", true && (T.getOS() == llvm::Triple::Win32) ? 1 : 0)
        .Case("cpu_dispatch", 1)
        .Case("cpu_specific", 1)
        .Case("callback", 1)
        .Case("code_align", 1)
        .Case("convergent", 1)
        .Case("diagnose_as_builtin", 1)
        .Case("disable_tail_calls", 1)
        .Case("enforce_tcb", 1)
        .Case("enforce_tcb_leaf", 1)
        .Case("enum_extensibility", 1)
        .Case("fallthrough", 1)
        .Case("flag_enum", 1)
        .Case("internal_linkage", 1)
        .Case("lto_visibility_public", 1)
        .Case("loader_uninitialized", 1)
        .Case("matrix_type", 1)
        .Case("maybe_undef", 1)
        .Case("minsize", 1)
        .Case("min_vector_width", 1)
        .Case("musttail", 1)
        .Case("neon_polyvector_type", 1)
        .Case("neon_vector_type", 1)
        .Case("no_builtin", 1)
        .Case("noderef", 1)
        .Case("no_destroy", 1)
        .Case("noduplicate", 1)
        .Case("noescape", 1)
        .Case("noinline", 1)
        .Case("nomerge", 1)
        .Case("no_speculative_load_hardening", 1)
        .Case("no_stack_protector", 1)
        .Case("nouwtable", 1)
        .Case("not_tail_called", 1)
        .Case("optnone", 1)
        .Case("overloadable", 1)
        .Case("pass_object_size", 1)
        .Case("pass_dynamic_object_size", 1)
        .Case("preferred_type", 1)
        .Case("preserve_all", 1)
        .Case("preserve_most", 1)
        .Case("enforce_read_only_placement", 1)
        .Case("release_handle", 1)
        .Case("speculative_load_hardening", 1)
        .Case("suppress", 1)
        .Case("type_tag_for_datatype", 1)
        .Case("type_visibility", 1)
        .Case("unavailable", 1)
        .Case("uninitialized", 1)
        .Case("unsafe_buffer_usage", 1)
        .Case("use_handle", 1)
        .Case("vectorcall", 1)
        .Case("warn_unused_result", 1)
        .Case("weak_import", 1)
        .Default(0);
  }
} break;
case AttributeCommonInfo::Syntax::AS_C23: {
  if (ScopeName == "") {
    return llvm::StringSwitch<int>(Name)
        .Case("deprecated", 201904)
        .Case("fallthrough", 201910)
        .Case("noreturn", 202202)
        .Case("_Noreturn", 202202)
        .Case("maybe_unused", 202106)
        .Case("nodiscard", 202003)
        .Default(0);
  } else if (ScopeName == "clang") {
    return llvm::StringSwitch<int>(Name)
        .Case("aarch64_sve_pcs", 1)
        .Case("aarch64_vector_pcs", 1)
        .Case("acquire_handle", 1)
        .Case("address_space", 1)
        .Case("annotate", 1)
        .Case("argument_with_type_tag", 1)
        .Case("pointer_with_type_tag", 1)
        .Case("__neverc_arm_builtin_alias",
              true && (T.getArch() == llvm::Triple::aarch64) ? 1 : 0)
        .Case("assume", 1)
        .Case("availability", 1)
        .Case("available_only_in_default_eval_method", 1)
        .Case("btf_decl_tag", 1)
        .Case("btf_type_tag", 1)
        .Case("guard", true && (T.getOS() == llvm::Triple::Win32) ? 1 : 0)
        .Case("cpu_dispatch", 1)
        .Case("cpu_specific", 1)
        .Case("callback", 1)
        .Case("code_align", 1)
        .Case("convergent", 1)
        .Case("diagnose_as_builtin", 1)
        .Case("disable_tail_calls", 1)
        .Case("enforce_tcb", 1)
        .Case("enforce_tcb_leaf", 1)
        .Case("enum_extensibility", 1)
        .Case("flag_enum", 1)
        .Case("internal_linkage", 1)
        .Case("lto_visibility_public", 1)
        .Case("loader_uninitialized", 1)
        .Case("matrix_type", 1)
        .Case("maybe_undef", 1)
        .Case("minsize", 1)
        .Case("min_vector_width", 1)
        .Case("musttail", 1)
        .Case("neon_polyvector_type", 1)
        .Case("neon_vector_type", 1)
        .Case("no_builtin", 1)
        .Case("noderef", 1)
        .Case("noduplicate", 1)
        .Case("noescape", 1)
        .Case("nomerge", 1)
        .Case("no_speculative_load_hardening", 1)
        .Case("no_stack_protector", 1)
        .Case("nouwtable", 1)
        .Case("not_tail_called", 1)
        .Case("optnone", 1)
        .Case("overloadable", 1)
        .Case("pass_object_size", 1)
        .Case("pass_dynamic_object_size", 1)
        .Case("preferred_type", 1)
        .Case("preserve_all", 1)
        .Case("preserve_most", 1)
        .Case("enforce_read_only_placement", 1)
        .Case("release_handle", 1)
        .Case("speculative_load_hardening", 1)
        .Case("suppress", 1)
        .Case("type_tag_for_datatype", 1)
        .Case("type_visibility", 1)
        .Case("unavailable", 1)
        .Case("unsafe_buffer_usage", 1)
        .Case("use_handle", 1)
        .Case("vectorcall", 1)
        .Case("weak_import", 1)
        .Default(0);
  } else if (ScopeName == "gnu") {
    return llvm::StringSwitch<int>(Name)
        .Case("alias", 1)
        .Case("aligned", 1)
        .Case("alloc_align", 1)
        .Case("alloc_size", 1)
        .Case("always_inline", 1)
        .Case("interrupt",
              true && (T.getArch() == llvm::Triple::x86_64) ? 1 : 0)
        .Case("no_caller_saved_registers",
              true && (T.getArch() == llvm::Triple::x86_64) ? 1 : 0)
        .Case("nocf_check",
              true && (T.getArch() == llvm::Triple::x86_64) ? 1 : 0)
        .Case("artificial", 1)
        .Case("assume_aligned", 1)
        .Case("cdecl", 1)
        .Case("cleanup", 1)
        .Case("cold", 1)
        .Case("common", 1)
        .Case("const", 1)
        .Case("__const", 1)
        .Case("constructor", 1)
        .Case("dllexport",
              true && (Target.getTriple().hasDLLImportExport()) ? 1 : 0)
        .Case("dllimport",
              true && (Target.getTriple().hasDLLImportExport()) ? 1 : 0)
        .Case("deprecated", 1)
        .Case("destructor", 1)
        .Case("disable_try_stmt", 1)
        .Case("error", 1)
        .Case("warning", 1)
        .Case("fallthrough", 1)
        .Case("fastcall", 1)
        .Case("flatten", 1)
        .Case("format", 1)
        .Case("format_arg", 1)
        .Case("function_return",
              true && (T.getArch() == llvm::Triple::x86_64) ? 1 : 0)
        .Case("gnu_inline", 1)
        .Case("hot", 1)
        .Case("ifunc", true && (T.getObjectFormat() == llvm::Triple::ELF ||
                                T.getObjectFormat() == llvm::Triple::MachO)
                           ? 1
                           : 0)
        .Case("leaf", 1)
        .Case("ms_abi", 1)
        .Case("ms_struct", 1)
        .Case("may_alias", 1)
        .Case("mode", 1)
        .Case("naked", 1)
        .Case("nocommon", 1)
        .Case("nodebug", 1)
        .Case("noinline", 1)
        .Case("no_randomize_layout", 1)
        .Case("noreturn", 1)
        .Case("no_split_stack", 1)
        .Case("no_stack_protector", 1)
        .Case("nothrow", 1)
        .Case("nonnull", 1)
        .Case("override", 1)
        .Case("packed", 1)
        .Case("patchable_function_entry",
              true && (T.getArch() == llvm::Triple::aarch64 ||
                       T.getArch() == llvm::Triple::x86 ||
                       T.getArch() == llvm::Triple::x86_64)
                  ? 1
                  : 0)
        .Case("pure", 1)
        .Case("randomize_layout", 1)
        .Case("regcall", 1)
        .Case("regparm", 1)
        .Case("malloc", 1)
        .Case("retain", 1)
        .Case("returns_nonnull", 1)
        .Case("returns_twice", 1)
        .Case("section", 1)
        .Case("selectany", 1)
        .Case("sentinel", 1)
        .Case("stdcall", 1)
        .Case("sysv_abi", 1)
        .Case("tls_model", 1)
        .Case("target", 1)
        .Case("target_clones", 1)
        .Case("target_version", 1)
        .Case("transparent_union", 1)
        .Case("unused", 1)
        .Case("used", 1)
        .Case("vector_size", 1)
        .Case("visibility", 1)
        .Case("volatile", 1)
        .Case("warn_unused", 1)
        .Case("warn_unused_result", 1)
        .Case("weak", 1)
        .Case("weakref", 1)
        .Case("force_align_arg_pointer",
              true && (T.getArch() == llvm::Triple::x86_64) ? 1 : 0)
        .Case("zero_call_used_regs", 1)
        .Default(0);
  } else if (ScopeName == "neverc") {
    return llvm::StringSwitch<int>(Name)
        .Case("aarch64_sve_pcs", 1)
        .Case("aarch64_vector_pcs", 1)
        .Case("acquire_handle", 1)
        .Case("address_space", 1)
        .Case("always_inline", 1)
        .Case("annotate", 1)
        .Case("annotate_type", 1)
        .Case("argument_with_type_tag", 1)
        .Case("pointer_with_type_tag", 1)
        .Case("__neverc_arm_builtin_alias",
              true && (T.getArch() == llvm::Triple::aarch64) ? 1 : 0)
        .Case("assume", 1)
        .Case("availability", 1)
        .Case("available_only_in_default_eval_method", 1)
        .Case("btf_decl_tag", 1)
        .Case("btf_type_tag", 1)
        .Case("builtin_alias", 1)
        .Case("guard", true && (T.getOS() == llvm::Triple::Win32) ? 1 : 0)
        .Case("cpu_dispatch", 1)
        .Case("cpu_specific", 1)
        .Case("callback", 1)
        .Case("code_align", 1)
        .Case("convergent", 1)
        .Case("diagnose_as_builtin", 1)
        .Case("disable_tail_calls", 1)
        .Case("enforce_tcb", 1)
        .Case("enforce_tcb_leaf", 1)
        .Case("enum_extensibility", 1)
        .Case("flag_enum", 1)
        .Case("internal_linkage", 1)
        .Case("lto_visibility_public", 1)
        .Case("likely", 1)
        .Case("loader_uninitialized", 1)
        .Case("matrix_type", 1)
        .Case("maybe_undef", 1)
        .Case("minsize", 1)
        .Case("min_vector_width", 1)
        .Case("musttail", 1)
        .Case("neon_polyvector_type", 1)
        .Case("neon_vector_type", 1)
        .Case("no_builtin", 1)
        .Case("noderef", 1)
        .Case("noduplicate", 1)
        .Case("noescape", 1)
        .Case("noinline", 1)
        .Case("nomerge", 1)
        .Case("no_speculative_load_hardening", 1)
        .Case("no_stack_protector", 1)
        .Case("nouwtable", 1)
        .Case("not_tail_called", 1)
        .Case("optnone", 1)
        .Case("overloadable", 1)
        .Case("pass_object_size", 1)
        .Case("pass_dynamic_object_size", 1)
        .Case("preferred_type", 1)
        .Case("preserve_all", 1)
        .Case("preserve_most", 1)
        .Case("enforce_read_only_placement", 1)
        .Case("release_handle", 1)
        .Case("speculative_load_hardening", 1)
        .Case("suppress", 1)
        .Case("type_tag_for_datatype", 1)
        .Case("type_visibility", 1)
        .Case("unavailable", 1)
        .Case("unlikely", 1)
        .Case("unsafe_buffer_usage", 1)
        .Case("use_handle", 1)
        .Case("vectorcall", 1)
        .Case("weak_import", 1)
        .Default(0);
  }
} break;
case AttributeCommonInfo::Syntax::AS_Keyword:
case AttributeCommonInfo::Syntax::AS_ContextSensitiveKeyword:
  llvm_unreachable("hasAttribute not supported for keyword");
  return 0;
case AttributeCommonInfo::Syntax::AS_Implicit:
  llvm_unreachable("hasAttribute not supported for AS_Implicit");
  return 0;
}
