#define NEVERC_ATTR_LIST_CanPrintOnLeft                                        \
  case attr::AArch64SVEPcs:                                                    \
  case attr::AArch64VectorPcs:                                                 \
  case attr::AcquireHandle:                                                    \
  case attr::AddressSpace:                                                     \
  case attr::Alias:                                                            \
  case attr::AlignValue:                                                       \
  case attr::Aligned:                                                          \
  case attr::AllocAlign:                                                       \
  case attr::AllocSize:                                                        \
  case attr::AlwaysDestroy:                                                    \
  case attr::AlwaysInline:                                                     \
  case attr::AnalyzerNoReturn:                                                 \
  case attr::Annotate:                                                         \
  case attr::AnnotateType:                                                     \
  case attr::AnyX86Interrupt:                                                  \
  case attr::AnyX86NoCallerSavedRegisters:                                     \
  case attr::AnyX86NoCfCheck:                                                  \
  case attr::ArgumentWithTypeTag:                                              \
  case attr::ArmBuiltinAlias:                                                  \
  case attr::ArmLocallyStreaming:                                              \
  case attr::ArmNewZA:                                                         \
  case attr::ArmPreservesZA:                                                   \
  case attr::ArmSharedZA:                                                      \
  case attr::ArmStreaming:                                                     \
  case attr::ArmStreamingCompatible:                                           \
  case attr::Artificial:                                                       \
  case attr::AssumeAligned:                                                    \
  case attr::Assumption:                                                       \
  case attr::Availability:                                                     \
  case attr::AvailableOnlyInDefaultEvalMethod:                                 \
  case attr::BTFDeclTag:                                                       \
  case attr::BTFTypeTag:                                                       \
  case attr::Builtin:                                                          \
  case attr::BuiltinAlias:                                                     \
  case attr::C11NoReturn:                                                      \
  case attr::CDecl:                                                            \
  case attr::CFGuard:                                                          \
  case attr::CPUDispatch:                                                      \
  case attr::CPUSpecific:                                                      \
  case attr::Callback:                                                         \
  case attr::CarriesDependency:                                                \
  case attr::Cleanup:                                                          \
  case attr::CodeAlign:                                                        \
  case attr::CodeSeg:                                                          \
  case attr::Cold:                                                             \
  case attr::Common:                                                           \
  case attr::Const:                                                            \
  case attr::Constructor:                                                      \
  case attr::Convergent:                                                       \
  case attr::DLLExport:                                                        \
  case attr::DLLImport:                                                        \
  case attr::Deprecated:                                                       \
  case attr::Destructor:                                                       \
  case attr::DiagnoseAsBuiltin:                                                \
  case attr::DisableTailCalls:                                                 \
  case attr::DisableTryStmt:                                                   \
  case attr::EnforceTCB:                                                       \
  case attr::EnforceTCBLeaf:                                                   \
  case attr::EnumExtensibility:                                                \
  case attr::Error:                                                            \
  case attr::FallThrough:                                                      \
  case attr::FastCall:                                                         \
  case attr::FlagEnum:                                                         \
  case attr::Flatten:                                                          \
  case attr::Format:                                                           \
  case attr::FormatArg:                                                        \
  case attr::FunctionReturnThunks:                                             \
  case attr::GNUInline:                                                        \
  case attr::Hot:                                                              \
  case attr::IFunc:                                                            \
  case attr::InitSeg:                                                          \
  case attr::InternalLinkage:                                                  \
  case attr::LTOVisibilityPublic:                                              \
  case attr::Leaf:                                                             \
  case attr::Likely:                                                           \
  case attr::LoaderUninitialized:                                              \
  case attr::MSABI:                                                            \
  case attr::MSAllocator:                                                      \
  case attr::MSStruct:                                                         \
  case attr::MaxFieldAlignment:                                                \
  case attr::MayAlias:                                                         \
  case attr::MaybeUndef:                                                       \
  case attr::MinSize:                                                          \
  case attr::MinVectorWidth:                                                   \
  case attr::Mode:                                                             \
  case attr::MustTail:                                                         \
  case attr::Naked:                                                            \
  case attr::NoAlias:                                                          \
  case attr::NoBuiltin:                                                        \
  case attr::NoCommon:                                                         \
  case attr::NoDebug:                                                          \
  case attr::NoDeref:                                                          \
  case attr::NoDestroy:                                                        \
  case attr::NoDuplicate:                                                      \
  case attr::NoEscape:                                                         \
  case attr::NoInline:                                                         \
  case attr::NoMerge:                                                          \
  case attr::NoRandomizeLayout:                                                \
  case attr::NoReturn:                                                         \
  case attr::NoSpeculativeLoadHardening:                                       \
  case attr::NoSplitStack:                                                     \
  case attr::NoStackProtector:                                                 \
  case attr::NoThrow:                                                          \
  case attr::NoUwtable:                                                        \
  case attr::NonNull:                                                          \
  case attr::NotTailCalled:                                                    \
  case attr::OptimizeNone:                                                     \
  case attr::Overloadable:                                                     \
  case attr::Override:                                                         \
  case attr::Packed:                                                           \
  case attr::PassObjectSize:                                                   \
  case attr::PatchableFunctionEntry:                                           \
  case attr::PragmaNeverCBSSSection:                                           \
  case attr::PragmaNeverCDataSection:                                          \
  case attr::PragmaNeverCRelroSection:                                         \
  case attr::PragmaNeverCRodataSection:                                        \
  case attr::PragmaNeverCTextSection:                                          \
  case attr::PreferredType:                                                    \
  case attr::PreserveAll:                                                      \
  case attr::PreserveMost:                                                     \
  case attr::Ptr32:                                                            \
  case attr::Ptr64:                                                            \
  case attr::Pure:                                                             \
  case attr::RandomizeLayout:                                                  \
  case attr::ReadOnlyPlacement:                                                \
  case attr::RegCall:                                                          \
  case attr::ReleaseHandle:                                                    \
  case attr::Restrict:                                                         \
  case attr::Retain:                                                           \
  case attr::ReturnsNonNull:                                                   \
  case attr::ReturnsTwice:                                                     \
  case attr::SPtr:                                                             \
  case attr::Section:                                                          \
  case attr::SelectAny:                                                        \
  case attr::Sentinel:                                                         \
  case attr::SpeculativeLoadHardening:                                         \
  case attr::StandardNoReturn:                                                 \
  case attr::StdCall:                                                          \
  case attr::StrictFP:                                                         \
  case attr::StrictGuardStackCheck:                                            \
  case attr::Suppress:                                                         \
  case attr::SysVABI:                                                          \
  case attr::TLSModel:                                                         \
  case attr::Target:                                                           \
  case attr::TargetClones:                                                     \
  case attr::TargetVersion:                                                    \
  case attr::Thread:                                                           \
  case attr::TransparentUnion:                                                 \
  case attr::TypeNonNull:                                                      \
  case attr::TypeNullUnspecified:                                              \
  case attr::TypeNullable:                                                     \
  case attr::TypeTagForDatatype:                                               \
  case attr::TypeVisibility:                                                   \
  case attr::UPtr:                                                             \
  case attr::Unavailable:                                                      \
  case attr::Uninitialized:                                                    \
  case attr::Unlikely:                                                         \
  case attr::UnsafeBufferUsage:                                                \
  case attr::Unused:                                                           \
  case attr::UseHandle:                                                        \
  case attr::Used:                                                             \
  case attr::VectorCall:                                                       \
  case attr::Visibility:                                                       \
  case attr::Volatile:                                                         \
  case attr::WarnUnused:                                                       \
  case attr::WarnUnusedResult:                                                 \
  case attr::Weak:                                                             \
  case attr::WeakImport:                                                       \
  case attr::WeakRef:                                                          \
  case attr::X86ForceAlignArgPointer:                                          \
  case attr::ZeroCallUsedRegs:
