KEYWORD_ATTRIBUTE(__arm_locally_streaming)
KEYWORD_ATTRIBUTE(__arm_new_za)
KEYWORD_ATTRIBUTE(__arm_preserves_za)
KEYWORD_ATTRIBUTE(__arm_shared_za)
KEYWORD_ATTRIBUTE(__arm_streaming)
KEYWORD_ATTRIBUTE(__arm_streaming_compatible)
#undef KEYWORD_ATTRIBUTE
