#if defined(NEVERC_ATTR_ARG_CONTEXT_LIST)
#endif // NEVERC_ATTR_ARG_CONTEXT_LIST

#if defined(NEVERC_ATTR_IDENTIFIER_ARG_LIST)
.Case("argument_with_type_tag", true)
    .Case("pointer_with_type_tag", true)
    .Case("__neverc_arm_builtin_alias", true)
    .Case("availability", true)
    .Case("builtin_alias", true)
    .Case("neverc_builtin_alias", true)
    .Case("guard", true)
    .Case("enum_extensibility", true)
    .Case("format", true)
    .Case("function_return", true)
    .Case("mode", true)
    .Case("type_tag_for_datatype", true)
    .Case("type_visibility", true)
    .Case("visibility", true)
    .Case("zero_call_used_regs", true)
#endif // NEVERC_ATTR_IDENTIFIER_ARG_LIST

#if defined(NEVERC_ATTR_STRING_LITERAL_ARG_LIST)
    .Case("acquire_handle", 1)
    .Case("alias", 1)
    .Case("annotate", 1)
    .Case("annotate_type", 1)
    .Case("asm", 1)
    .Case("__asm__", 1)
    .Case("assume", 1)
    .Case("availability", 160)
    .Case("btf_decl_tag", 1)
    .Case("btf_type_tag", 1)
    .Case("code_seg", 1)
    .Case("deprecated", 3)
    .Case("diagnose_if", 2)
    .Case("enable_if", 2)
    .Case("enforce_tcb", 1)
    .Case("enforce_tcb_leaf", 1)
    .Case("error", 1)
    .Case("warning", 1)
    .Case("ifunc", 1)
    .Case("init_seg", 1)
    .Case("no_builtin", 4294967295)
    .Case("release_handle", 1)
    .Case("section", 1)
    .Case("allocate", 1)
    .Case("suppress", 4294967295)
    .Case("tls_model", 1)
    .Case("target", 1)
    .Case("target_clones", 4294967295)
    .Case("target_version", 1)
    .Case("unavailable", 1)
    .Case("use_handle", 1)
    .Case("nodiscard", 1)
    .Case("warn_unused_result", 1)
    .Case("weakref", 1)
#endif // NEVERC_ATTR_STRING_LITERAL_ARG_LIST

#if defined(NEVERC_ATTR_VARIADIC_IDENTIFIER_ARG_LIST)
    .Case("cpu_dispatch", true)
    .Case("cpu_specific", true)
    .Case("callback", true)
#endif // NEVERC_ATTR_VARIADIC_IDENTIFIER_ARG_LIST

#if defined(NEVERC_ATTR_THIS_ISA_IDENTIFIER_ARG_LIST)
    .Case("callback", true)
#endif // NEVERC_ATTR_THIS_ISA_IDENTIFIER_ARG_LIST

#if defined(NEVERC_ATTR_TYPE_ARG_LIST)
    .Case("preferred_type", true)
#endif // NEVERC_ATTR_TYPE_ARG_LIST

#if defined(NEVERC_ATTR_LATE_PARSED_LIST)
    .Case("diagnose_if", 1)
#endif // NEVERC_ATTR_LATE_PARSED_LIST
