/*
 * SHA-512/256 — FIPS 180-4, Section 6.7.
 * Same compression as SHA-512, different IV, output truncated to 32 bytes.
 * IV generated by SHA-512("SHA-512/256") as specified in FIPS 180-4 Section 5.3.6.
 */
#include "neverc/sha512_256.h"
#include <string.h>

void neverc_sha512_256_init(neverc_sha512_256_ctx *ctx) {
    ctx->state[0] = 0x22312194FC2BF72CULL;
    ctx->state[1] = 0x9F555FA3C84C64C2ULL;
    ctx->state[2] = 0x2393B86B6F53B151ULL;
    ctx->state[3] = 0x963877195940EABDULL;
    ctx->state[4] = 0x96283EE2A88EFFE3ULL;
    ctx->state[5] = 0xBE5E1E2553863992ULL;
    ctx->state[6] = 0x2B0199FC2C85B8AAULL;
    ctx->state[7] = 0x0EB72DDC81C52CA2ULL;
    ctx->count = 0;
    memset(ctx->buf, 0, sizeof(ctx->buf));
}

void neverc_sha512_256_update(neverc_sha512_256_ctx *ctx, const uint8_t *data, size_t len) {
    neverc_sha512_update(ctx, data, len);
}

void neverc_sha512_256_final(neverc_sha512_256_ctx *ctx, uint8_t digest[32]) {
    uint8_t full[64];
    neverc_sha512_final(ctx, full);
    memcpy(digest, full, 32);
}

void neverc_sha512_256_sum(const uint8_t *data, size_t len, uint8_t digest[32]) {
    neverc_sha512_256_ctx ctx;
    neverc_sha512_256_init(&ctx);
    neverc_sha512_256_update(&ctx, data, len);
    neverc_sha512_256_final(&ctx, digest);
}
