static void _neverc_krt_ll_handler_0(neverc_krt_reg_ctx *ctx)
{ _neverc_krt_ll_invoke(0, ctx); }
static void _neverc_krt_ll_handler_1(neverc_krt_reg_ctx *ctx)
{ _neverc_krt_ll_invoke(1, ctx); }
static void _neverc_krt_ll_handler_2(neverc_krt_reg_ctx *ctx)
{ _neverc_krt_ll_invoke(2, ctx); }
static void _neverc_krt_ll_handler_3(neverc_krt_reg_ctx *ctx)
{ _neverc_krt_ll_invoke(3, ctx); }
static void _neverc_krt_ll_handler_4(neverc_krt_reg_ctx *ctx)
{ _neverc_krt_ll_invoke(4, ctx); }
static void _neverc_krt_ll_handler_5(neverc_krt_reg_ctx *ctx)
{ _neverc_krt_ll_invoke(5, ctx); }
static void _neverc_krt_ll_handler_6(neverc_krt_reg_ctx *ctx)
{ _neverc_krt_ll_invoke(6, ctx); }
static void _neverc_krt_ll_handler_7(neverc_krt_reg_ctx *ctx)
{ _neverc_krt_ll_invoke(7, ctx); }
static void _neverc_krt_ll_handler_8(neverc_krt_reg_ctx *ctx)
{ _neverc_krt_ll_invoke(8, ctx); }
static void _neverc_krt_ll_handler_9(neverc_krt_reg_ctx *ctx)
{ _neverc_krt_ll_invoke(9, ctx); }
static void _neverc_krt_ll_handler_10(neverc_krt_reg_ctx *ctx)
{ _neverc_krt_ll_invoke(10, ctx); }
static void _neverc_krt_ll_handler_11(neverc_krt_reg_ctx *ctx)
{ _neverc_krt_ll_invoke(11, ctx); }
static void _neverc_krt_ll_handler_12(neverc_krt_reg_ctx *ctx)
{ _neverc_krt_ll_invoke(12, ctx); }
static void _neverc_krt_ll_handler_13(neverc_krt_reg_ctx *ctx)
{ _neverc_krt_ll_invoke(13, ctx); }
static void _neverc_krt_ll_handler_14(neverc_krt_reg_ctx *ctx)
{ _neverc_krt_ll_invoke(14, ctx); }
static void _neverc_krt_ll_handler_15(neverc_krt_reg_ctx *ctx)
{ _neverc_krt_ll_invoke(15, ctx); }
static void _neverc_krt_ll_handler_16(neverc_krt_reg_ctx *ctx)
{ _neverc_krt_ll_invoke(16, ctx); }
static void _neverc_krt_ll_handler_17(neverc_krt_reg_ctx *ctx)
{ _neverc_krt_ll_invoke(17, ctx); }
static void _neverc_krt_ll_handler_18(neverc_krt_reg_ctx *ctx)
{ _neverc_krt_ll_invoke(18, ctx); }
static void _neverc_krt_ll_handler_19(neverc_krt_reg_ctx *ctx)
{ _neverc_krt_ll_invoke(19, ctx); }
static void _neverc_krt_ll_handler_20(neverc_krt_reg_ctx *ctx)
{ _neverc_krt_ll_invoke(20, ctx); }
static void _neverc_krt_ll_handler_21(neverc_krt_reg_ctx *ctx)
{ _neverc_krt_ll_invoke(21, ctx); }
static void _neverc_krt_ll_handler_22(neverc_krt_reg_ctx *ctx)
{ _neverc_krt_ll_invoke(22, ctx); }
static void _neverc_krt_ll_handler_23(neverc_krt_reg_ctx *ctx)
{ _neverc_krt_ll_invoke(23, ctx); }
static void _neverc_krt_ll_handler_24(neverc_krt_reg_ctx *ctx)
{ _neverc_krt_ll_invoke(24, ctx); }
static void _neverc_krt_ll_handler_25(neverc_krt_reg_ctx *ctx)
{ _neverc_krt_ll_invoke(25, ctx); }
static void _neverc_krt_ll_handler_26(neverc_krt_reg_ctx *ctx)
{ _neverc_krt_ll_invoke(26, ctx); }
static void _neverc_krt_ll_handler_27(neverc_krt_reg_ctx *ctx)
{ _neverc_krt_ll_invoke(27, ctx); }
static void _neverc_krt_ll_handler_28(neverc_krt_reg_ctx *ctx)
{ _neverc_krt_ll_invoke(28, ctx); }
static void _neverc_krt_ll_handler_29(neverc_krt_reg_ctx *ctx)
{ _neverc_krt_ll_invoke(29, ctx); }
static void _neverc_krt_ll_handler_30(neverc_krt_reg_ctx *ctx)
{ _neverc_krt_ll_invoke(30, ctx); }
static void _neverc_krt_ll_handler_31(neverc_krt_reg_ctx *ctx)
{ _neverc_krt_ll_invoke(31, ctx); }

static neverc_krt_ctx_handler_t _neverc_krt_ll_handlers[NEVERC_KRT_LL_MAX] = {
	[0] = _neverc_krt_ll_handler_0,
	[1] = _neverc_krt_ll_handler_1,
	[2] = _neverc_krt_ll_handler_2,
	[3] = _neverc_krt_ll_handler_3,
	[4] = _neverc_krt_ll_handler_4,
	[5] = _neverc_krt_ll_handler_5,
	[6] = _neverc_krt_ll_handler_6,
	[7] = _neverc_krt_ll_handler_7,
	[8] = _neverc_krt_ll_handler_8,
	[9] = _neverc_krt_ll_handler_9,
	[10] = _neverc_krt_ll_handler_10,
	[11] = _neverc_krt_ll_handler_11,
	[12] = _neverc_krt_ll_handler_12,
	[13] = _neverc_krt_ll_handler_13,
	[14] = _neverc_krt_ll_handler_14,
	[15] = _neverc_krt_ll_handler_15,
	[16] = _neverc_krt_ll_handler_16,
	[17] = _neverc_krt_ll_handler_17,
	[18] = _neverc_krt_ll_handler_18,
	[19] = _neverc_krt_ll_handler_19,
	[20] = _neverc_krt_ll_handler_20,
	[21] = _neverc_krt_ll_handler_21,
	[22] = _neverc_krt_ll_handler_22,
	[23] = _neverc_krt_ll_handler_23,
	[24] = _neverc_krt_ll_handler_24,
	[25] = _neverc_krt_ll_handler_25,
	[26] = _neverc_krt_ll_handler_26,
	[27] = _neverc_krt_ll_handler_27,
	[28] = _neverc_krt_ll_handler_28,
	[29] = _neverc_krt_ll_handler_29,
	[30] = _neverc_krt_ll_handler_30,
	[31] = _neverc_krt_ll_handler_31,
};
