#ifndef NEVERC_NETWORK_TEST_CERTS_H
#define NEVERC_NETWORK_TEST_CERTS_H

#define NEVERC_TEST_CA_CERT_PEM \
    "-----BEGIN CERTIFICATE-----\n" \
    "MIIBpjCCAU2gAwIBAgIUCmt+KkwZayFHFj97YlD5Beb8ptwwCgYIKoZIzj0EAwIw\n" \
    "ITEfMB0GA1UEAwwWTmV2ZXJDIE5ldHdvcmsgVGVzdCBDQTAeFw0yNjA4MDExNDIx\n" \
    "MzRaFw0zNjA3MjkxNDIxMzRaMCExHzAdBgNVBAMMFk5ldmVyQyBOZXR3b3JrIFRl\n" \
    "c3QgQ0EwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQCQUgO7yEyUkO4qXRXwGiy\n" \
    "x/koa5Lw5jpljzLvE/VXhQTzbMg5tcdmKkz4lW++rYknEdrg5PNzry0lN7Fs3Ii0\n" \
    "o2MwYTAdBgNVHQ4EFgQU+EwMJdb1v4BRmCBDQuSjgv057nUwHwYDVR0jBBgwFoAU\n" \
    "+EwMJdb1v4BRmCBDQuSjgv057nUwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8E\n" \
    "BAMCAQYwCgYIKoZIzj0EAwIDRwAwRAIgcgrZ8n6jByigCJb+5O4ra1U9Odqcyy6y\n" \
    "/KyulPU8hqACICbNgEzC35cQQt8dC9XBzPR9rfspsmE/TQ8eXHcsjDl0\n" \
    "-----END CERTIFICATE-----\n"

#define NEVERC_TEST_SERVER_CERT_PEM \
    "-----BEGIN CERTIFICATE-----\n" \
    "MIIByTCCAXCgAwIBAgIUQGwMtg4p89vn2G+wQ/tYuJnHInwwCgYIKoZIzj0EAwIw\n" \
    "ITEfMB0GA1UEAwwWTmV2ZXJDIE5ldHdvcmsgVGVzdCBDQTAeFw0yNjA4MDExNDIx\n" \
    "MzRaFw0zNjA3MjkxNDIxMzRaMBQxEjAQBgNVBAMMCWxvY2FsaG9zdDBZMBMGByqG\n" \
    "SM49AgEGCCqGSM49AwEHA0IABMshHwgjbHo0TJKzc5wjiPQY7zUV/vBKlNqnUdve\n" \
    "HVAv+KchaXzmyMmvRD0VM+x6KxSgDi2AI0I0ttOerr7SdUqjgZIwgY8wGgYDVR0R\n" \
    "BBMwEYIJbG9jYWxob3N0hwR/AAABMAwGA1UdEwEB/wQCMAAwDgYDVR0PAQH/BAQD\n" \
    "AgeAMBMGA1UdJQQMMAoGCCsGAQUFBwMBMB0GA1UdDgQWBBST7aKUDPudhpnjEViy\n" \
    "oXkUG0j23jAfBgNVHSMEGDAWgBT4TAwl1vW/gFGYIENC5KOC/TnudTAKBggqhkjO\n" \
    "PQQDAgNHADBEAiBbfTAd7t2iGb3hhrtGz3Tg3MrhWQrV1UA8lz8nAeDl7gIgU4PT\n" \
    "6OwihFnZIAVSaPuiZ4sWkFEMecKY5WCJTQLpUI0=\n" \
    "-----END CERTIFICATE-----\n"

#define NEVERC_TEST_SERVER_KEY_PEM \
    "-----BEGIN EC PRIVATE KEY-----\n" \
    "MHcCAQEEIIziEpngGXizdmAiyKYgtfJwdzxFGzrX7I+8ZVI5BXPBoAoGCCqGSM49\n" \
    "AwEHoUQDQgAEyyEfCCNsejRMkrNznCOI9BjvNRX+8EqU2qdR294dUC/4pyFpfObI\n" \
    "ya9EPRUz7HorFKAOLYAjQjS2056uvtJ1Sg==\n" \
    "-----END EC PRIVATE KEY-----\n"

#define NEVERC_TEST_CLIENT_CERT_PEM \
    "-----BEGIN CERTIFICATE-----\n" \
    "MIIBsTCCAVegAwIBAgIUQGwMtg4p89vn2G+wQ/tYuJnHIn0wCgYIKoZIzj0EAwIw\n" \
    "ITEfMB0GA1UEAwwWTmV2ZXJDIE5ldHdvcmsgVGVzdCBDQTAeFw0yNjA4MDExNDIx\n" \
    "MzRaFw0zNjA3MjkxNDIxMzRaMBkxFzAVBgNVBAMMDm5ldmVyYy1hZ2VudC0xMFkw\n" \
    "EwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEceu4tIHEa75sqhbx24e3MYziUxAXiEq/\n" \
    "04DEX8GTqmaF6KnIyuD5DK+tXVZkaOm2iJF3EUsWn/zW4MdsgOndf6N1MHMwDAYD\n" \
    "VR0TAQH/BAIwADAOBgNVHQ8BAf8EBAMCB4AwEwYDVR0lBAwwCgYIKwYBBQUHAwIw\n" \
    "HQYDVR0OBBYEFJ20hoAOV4n4yZ4HhAyz3n5PryiTMB8GA1UdIwQYMBaAFPhMDCXW\n" \
    "9b+AUZggQ0Lko4L9Oe51MAoGCCqGSM49BAMCA0gAMEUCIHuV++e8tc/HgUHPsy+9\n" \
    "/mJiDgTdCJ6f843nKlHjm/YxAiEAtMJNJH928ZLBZurLIz+yguvvfMEqKqPsUyoN\n" \
    "bUfGAUY=\n" \
    "-----END CERTIFICATE-----\n"

#define NEVERC_TEST_CLIENT_KEY_PEM \
    "-----BEGIN EC PRIVATE KEY-----\n" \
    "MHcCAQEEIL2pJaCSQQz9clnyZhW4SV0m3N8TO9DrFqyrdhy6m8RdoAoGCCqGSM49\n" \
    "AwEHoUQDQgAEceu4tIHEa75sqhbx24e3MYziUxAXiEq/04DEX8GTqmaF6KnIyuD5\n" \
    "DK+tXVZkaOm2iJF3EUsWn/zW4MdsgOndfw==\n" \
    "-----END EC PRIVATE KEY-----\n"

#endif
